apiVersion: v2
name: Buerokratt
description: Umbrella chart for Buerokratt
version: 0.1.0
type: application

dependencies:
  - name: Ruuter
    version: 0.1.0
    repository: "file://./charts/Ruuter"
  - name: Resql
    version: 0.1.0
    repository: "file://./charts/Resql"
  - name: Databases
    version: 0.1.20
    repository: "file://./charts/Databases"
  - name: TIM
    version: 0.1.0
    repository: "file://./charts/TIM"
  - name: Authentication-Layer
    version: 0.1.0
    repository: "file://./charts/Authentication-Layer"
  - name: CronManager
    version: 0.1.0
    repository: "file://./charts/CronManager"
  - name: DataMapper
    version: 0.1.0
    repository: "file://./charts/DataMapper"
  - name: Notification-server
    version: 0.1.0
    repository: "file://./charts/Notification-server"
  - name: OpenSearch
    version: 0.1.0
    repository: "file://./charts/OpenSearch"
  - name: Private-Ruuter
    version: 0.1.0
    repository: "file://./charts/Private-Ruuter"
  - name: minio
    version: 0.1.0
    repository: "file://./charts/minio"
  - name: mlflow
    version: 0.1.0
    repository: "file://./charts/mlflow"
  - name: GKLSF-GUI
    version: 0.1.0
    repository: "file://./charts/GKLSF-GUI"