Ruuter:
  release_name: "ruuteritest"
  domain: "eexample.com"
  images:
    scope:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/ruuter"
      # tag: "v2.2.2"
      tag: "latest"
  secretname: "ruuter_cert_name_here" #We use CertManager so use e.g ruuter.domain.ee.001
  env:
    cors: "https://xample.com"
    sizelimit: "3000"
Resql:
  istio:
    enabled: false
  domain: "eexample.com"

  release_name: "component-byk-resql"
  release_db: "component-databases" 

  images:
    scope:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/resql"
      # tag: "v1.3.4"
      tag: "latest"
    backoffice:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "backoffice-module-test-1.5.19"
      tag: "latest"
    analytics:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "analytics-module-test-1.5.11"
      tag: "latest"
    services:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "service-module-test-1.5.20"
      tag: "latest"
    training:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "training-module-test-1.5.18"
      tag: "latest"
      
  env:
    LOGGING_LEVEL_ROOT: "INFO"
    SQLMS_DATASOURCES_0_NAME: "byk"
    SQLMS_DATASOURCES_0_JDBCURL: "jdbc:postgresql://component-databases-users-db:5432/byk"
    SQLMS_DATASOURCES_0_USERNAME: "byk"
    SQLMS_DATASOURCES_0_PASSWORD: ""
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT: "DEBUG"

  resources:
    requests:
      memory: "1000Mi"
      cpu: "50m"
    limits:
      memory: "2000Mi"
      cpu: "50m"

Databases:
  domain: "eexample.com"
  releaseName: "component-databases"
  tim-postgresql:
    image:
      tag: 14.1.0
    auth:
      postgresPassword: postgres
      username: tim
      password: "{{ TIMDB.password }}"
      database: tim
    statefulset:
      enabled: true
      replicaCount: 1
      persistence:
        storageClass: longhorn
        enabled: true
        size: 1Gi
  users-db:
    image:
      tag: 14.1.0
    auth:
      postgresPassword: postgres
      username: byk
      password: "{{ usersDB.password }}"
      database: byk
    statefulset:
      enabled: true
      replicaCount: 1
      persistence:
        storageClass: longhorn
        enabled: true
        size: 1Gi

TIM:
  domain: "eexample.com"
  secretname: "tim.centops.example.ee0001"

  release_name: "component-byk-tim"
  release_db: "component-databases"

  byk:
    tim:
      env:
        security:
          allowlist:
            jwt: component-byk-ruuter,component-byk-ruuter-private,module-byk-widget,module-byk-authentication-layer,component-byk-tim,10.0.0.0/8,192.168.0.0/16
          oauth2:
            client:
              clientId: "example" 
              clientSecret: "example"
              scope: openid
              userAuthorizationUri: "https://tim.centops.example.com/oidc/authorize"
              accessTokenUri: "https://tim.centops.example.com/oidc/token"
            resource:
              jwk:
                keySetUri: "https://tim.centops.example.com/oidc/jwks"
        legacyPortalIntegration:
          legacyUrl: NA
          legacyPortalRefererMarker: NA
          sessionCookieDomain: "eexample.com"
        jwtIntegration:
          signature:
            issuer: "eexample.com"
            keyStorePassword: "password"
            keyStore: classpath:jwtkeystore.jks
        spring:
          profiles:
            active: dev
        logging:
          level:
            root: INFO
    key_pass: "keystorepassword"
  keystore: "keystorepassword"
        
  tim-postgresql:
    image:
      tag: 14.1.0
    auth:
      postgresPassword: postgres
      username: tim
      password: "timdbpassword"
      database: "tim"

  tim_postgresql: "timdbpassword"

  images:
    scope:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/tim"
      # tag: "v1.1.1"
      tag: "latest"

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "200m"

