apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Release.Namespace }}-mlflow-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.mlflow_data.size }}
