{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: "{{ .Values.release_name }}"
spec:
  host: "{{ .Values.release_name }}"
  subsets:
  - name: "{{ .Values.release_name }}"
    labels:
      app: "{{ .Values.release_name }}"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ .Values.release_name }}"
spec:
  hosts:
  - "{{ .Values.release_name }}"
  http:
  - name: allow
    match:
    - sourceLabels:
        app: "{{ .Values.release_name }}"
    route:
    - destination:
        host: "{{ .Values.release_name }}"
        subset: "{{ .Values.release_name }}"
  - name: reject
    route:
    - destination:
        host: "{{ .Values.release_name }}"
        subset: "{{ .Values.release_name }}"
    fault:
      abort:
        percentage:
          value: 100.0
        httpStatus: 403
{{- end }}
