{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  password: {{ .Values.database.secret.keys.POSTGRES_PASSWORD | quote }}
{{- end }}
