{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            {{- range .Values.database.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password
          ports:
            - containerPort: {{ .Values.database.service.port }}
          resources:
{{ toYaml .Values.database.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ if .Values.database.persistence.existingClaim }}{{ .Values.database.persistence.existingClaim }}{{ else }}{{ .Release.Name }}-db-pvc{{ end }}"
{{- end }}
