{{ if .Values.fileProcessing.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.fileProcessing.nameOverride }}-files-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fileProcessing.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.fileProcessing.nameOverride }}-logs-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fileProcessing.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrapped-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.fileProcessing.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.fileProcessing.persistence.size }}
{{- end }}