{{- if .Values.gui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.gui.nameOverride | default "gui" }}
  annotations:
{{- range $key, $value := .Values.gui.ingress.annotations }}
    {{ $key }}: {{ $value }}
{{- end }}

spec:
  ingressClassName: "nginx"

  rules:
    - host: {{ .Values.gui.ingress.host }}
      http:
        paths:
          - path: /ckb
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.gui.nameOverride | default "gui" }}
                port:
                  number: {{ .Values.gui.service.port }}

  tls:
    - hosts:
        - {{ .Values.gui.ingress.host }}
      secretName: {{ .Values.gui.ingress.tlsSecret }}

{{- end }}