{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.nameOverride }}
  labels:
    app: {{ .Values.rabbitmq.nameOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.nameOverride }}
    spec:
      containers:
        - name: {{ .Values.rabbitmq.nameOverride }}
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          env:
            {{- range .Values.rabbitmq.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.rabbitmq.service.amqpPort }}
            - containerPort: {{ .Values.rabbitmq.service.uiPort }}
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
              readOnly: true
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
{{- end }}
