{{- if .Values.resqlCkb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resqlCkb.nameOverride | default "resql-ckb" }}
  labels:
    app: {{ .Values.resqlCkb.nameOverride | default "resql-ckb" }}
spec:
  replicas: {{ .Values.resqlCkb.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.resqlCkb.nameOverride | default "resql-ckb" }}
  template:
    metadata:
      labels:
        app: {{ .Values.resqlCkb.nameOverride | default "resql-ckb" }}
    spec:
      volumes:
      - name: dsl
        emptyDir: {}
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          volumeMounts:
          - name: dsl
            mountPath: /DSL
          command:
            - sh
            - -c
            - |
                git clone --single-branch --depth 1 --branch dev https://github.com/buerokratt/Common-Knowledge.git /tmp/ckb &&
                cp -r /tmp/ckb/DSL/Resql/ckb /DSL/
                cp -r /tmp/ckb/DSL/Resql/users /DSL/
                cp -rv /DSL/users/GET/* /DSL/ckb/GET                
      containers:
        - name: {{ .Values.resqlCkb.nameOverride | default "resql-ckb" }}
          image: "{{ .Values.resqlCkb.image.repository }}:{{ .Values.resqlCkb.image.tag }}"
          imagePullPolicy: {{ .Values.resqlCkb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.resqlCkb.service.port }}
          volumeMounts:
            - name: dsl
              mountPath: /DSL
          env:
            {{- range .Values.resqlCkb.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resqlCkb.resources | nindent 12 }}
{{- end }}
