apiVersion: v1
kind: Secret
metadata:
  name: tim-env-secret
type: Opaque
data:
  oauth2_client_secret: "{{ .Values.tim.config.oauth2_client_secret | b64enc }}"
  jwt_integration_key_store_password: "{{ .Values.tim.config.jwt_keystore_password | b64enc }}"

