{{- if .Values.timPostgresql.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.timPostgresql.secret.name }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.timPostgresql.secret.keys.POSTGRES_PASSWORD | b64enc | quote }}
{{- end }}
