apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
spec:
  replicas: {{ .Values.azurite.replicaCount }}
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: s3-ferry
          image: "{{ .Values.images.ferry.repository }}:{{ .Values.images.ferry.tag }}"
          imagePullPolicy: {{ .Values.images.ferry.pullPolicy }}
          env:
            - name: API_CORS_ORIGIN
              value: "{{ .Values.azuriteenv.apiCorsOrigin }}"
            - name: API_DOCUMENTATION_ENABLED
              value: "{{ .Values.azuriteenv.apiDocumentationEnabled }}"
            - name: AZURE_ACCOUNT_1_CONNECTION_STRING
              value: "{{ .Values.azuriteenv.azureConnectionString }}"
          ports:
            - containerPort: 3000
      volumes:
        - name: azurite-data
          persistentVolumeClaim:
            claimName: azurite-pvc

