apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ namespace }}-services-dsl
spec:
  storageClassName: dsl
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
