apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: byk-{{ namespace }}-dsl-services
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

