apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Release.Namespace }}-minio-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.minio_data.size }}
