apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    app: "{{ .Values.release_name }}"
  ports:
    - port: {{ .Values.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.ports.console }}
      targetPort: console
      protocol: TCP
      name: console
