apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.release_name }}"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: "{{ .Values.release_name }}"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: db-init
          image: postgres:latest
          command:
            - /bin/sh
            - -c
            - |
              PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" <<EOF
              -- Your SQL commands here
              INSERT INTO public.user (login, first_name, last_name, id_code, display_name, status, created, csa_title, csa_email) VALUES ('{{ .Values.user.login }}', '{{ .Values.user.first_name }}', '{{ .Values.user.last_name }}', '{{ .Values.user.id_code }}', '{{ .Values.user.display_name }}', 'active', now(), '{{ .Values.user.csa_title }}', '{{ .Values.user.csa_email }}');
              INSERT INTO user_authority (user_id, authority_name, created) VALUES ((SELECT id_code FROM public.user WHERE login = '{{ .Values.user.login }}'), ARRAY['ROLE_ADMINISTRATOR'], now());
              -- End of SQL commands
              EOF
          env:
            - name: DB_HOST
              value: "{{ .Values.db.db_host }}"
            - name: DB_PORT
              value: "{{ .Values.db.db_port }}"
            - name: DB_USER
              value: "{{ .Values.db.db_user }}"
            - name: DB_NAME
              value: "{{ .Values.db.db_name }}"
            - name: DB_PASSWORD
              value: "{{ .Values.db.db_password }}"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
      restartPolicy: Never
