imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicas: 2
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: {{ domain.name }} # Domain name
secretname: {{ cert.Name.value }} # Cert name value, change this as suited to environment

istio:
  enabled: {{ istio.enabled }}

ingress:
  certIssuerName: {{ cert.Issuer.Name }} # Change this if your certIssuerName has set up different

release_name: "component-byk-ruuter-private"

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/ruuter"
    tag: "{{ component.ruuter.image.version }}" # Images (tags) are up to date, currently no changes needed
  backoffice:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "{{ module.backoffice.image.version }}" # Images (tags) are up to date, currently no changes needed
  analytics:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "{{ module.analytics.image.version }}" # Images (tags) are up to date, currently no changes needed
  services:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "{{ module.services.image.version }}" # Images (tags) are up to date, currently no changes needed
  training:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "{{ module.training.image.version }}" # Images (tags) are up to date, currently no changes needed 
env:
  LOGGING_LEVEL_ROOT: "INFO"
  LOG_LEVEL_TIMING: "INFO"
  APPLICATION_LOGGING_DISPLAY_REQUEST_CONTENT: "false"
  APPLICATION_LOGGING_DISPLAY_RESPONSE_CONTENT: "false"
  APPLICATION_HTTPCODESALLOWLIST: "200,201,202,204,400,401,403,500"
  application.internalRequests.allowedIPs: "127.0.0.1"
  APPLICATION_CORS_ALLOWED_ORIGINS: {{ url.name.admin }}, {{ url.name.domain }}, {{ url.name.tim }}, {{ url.name.ruuter }} # Change the domain name, leave subdomain and subpath same

  APPLICATION_OPENSEARCH_CONFIGURATION_URL: http://component-opensearch-node:9200

resources:
  requests:
    memory: "385Mi"
    cpu: "256m"
  limits:
    memory: "512Mi"
    cpu: "512m"
