nameOverride: component-byk-tim
fullnameOverride: component-byk-tim
replicaCount: 1
 
workload:
  kind: Deployment
  selectorLabels: {app: component-byk-tim}
podSecurityContext: {}

ingress: {enabled: false}
istio: {enabled: false}

env:
  - {name: security.allowlist.jwt, value: "component-byk-ruuter,component-byk-ruuter-private,module-byk-widget,module-byk-authentication-layer,component-byk-tim,10.0.0.0/8,192.168.0.0/16"}
  - {name: security.oauth2.client.clientId, value: "id"}
  - {name: security.oauth2.client.clientSecret, value: "Secret"}
  - {name: security.oauth2.client.scope, value: "openid"}
  - {name: security.oauth2.client.userAuthorizationUri, value: "https://example.com/oidc/authorize"}
  - {name: security.oauth2.client.accessTokenUri, value: "https://example.com/oidc/token"}
  - {name: security.oauth2.resource.jwk.keySetUri, value: "https://example.com/oidc/jwks"}
  - {name: legacyPortalIntegration.legacyUrl, value: "NA"}
  - {name: legacyPortalIntegration.legacyPortalRefererMarker, value: "NA"}
  - {name: legacyPortalIntegration.sessionCookieDomain, value: "https://example.com"}
  - {name: jwtIntegration.signature.issuer, value: "https://example.com"} # Change the domain name, leave subdomain and subpath same
  - {name: jwtIntegration.signature.keyStorePassword, value: "keystore"}
  - {name: jwtIntegration.signature.keyStore, value: "classpath:jwtkeystore.jks"}
  - {name: spring.profiles.active, value: "dev"}
  - {name: logging.level.root, value: "INFO"}
  - {name: key_pass, value: "keystore"}

image:
  repository: ghcr.io
  name: buerokratt/tim
  tag: "{{ component.tim.image.version }}"
  pullPolicy: IfNotPresent

resources:
  requests: {cpu: 250m, memory: 1000Mi}
  limits: {cpu: 250m, memory: 1000Mi}

startupProbe:
  httpGet:
    port: http
    path: /healthz
  periodSeconds: 5
  failureThreshold: 24
  initialDelaySeconds: 30

readinessProbe:
  httpGet:
    port: http
    path: /healthz
  periodSeconds: 5
  failureThreshold: 3

livenessProbe:
  httpGet:
    port: http
    path: /healthz
  periodSeconds: 10
  failureThreshold: 3

timconfig: |
  DOMAIN=example.invalid