imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: {{ domain.name }} # Domain name
secretname: {{ url.name.admin }} # Cert name value, change this as suited to environment

ingress:
  certIssuerName: {{ cert.Issuer.Name }} # Change this if your certIssuerName has set up different

release_name: "module-byk-backoffice-gui"


images:
  gui:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-chatbot"
    tag: "{{ module.backoffice.gui.version }}" # Images (tags) are up to date, currently no changes needed
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "{{ module.backoffice.image.version }}" # Images (tags) are up to date, currently no changes needed
  liquibase:
    dsl:
      repo: https://github.com/buerokratt/Buerokratt-Chatbot.git
      path: DSL/Liquibase

env:
  REACT_APP_RUUTER_API_URL: "{{ url.name.ruuter }}/v2/public/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_RUUTER_PRIVATE_API_URL: "{{ url.name.ruuter }}/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_BUEROKRATT_CHATBOT_URL: "{{ url.name.admin }}/chat" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MENU_URL: "{{ url.name.admin }}" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MENU_PATH: "/chat/menu.json"
  REACT_APP_CUSTOMER_SERVICE_LOGIN: "{{ url.name.admin }}/et/log-in" # Change the domain name, leave subdomain and subpath same
  DOMAIN: "{{ domain.name }}"
  REACT_APP_CONVERSATIONS_BASE_URL: "{{ url.name.admin }}/chat" # Change the domain name, leave subdomain and subpath same
  REACT_APP_TRAINING_BASE_URL: "{{ url.name.admin }}/training" # Change the domain name, leave subdomain and subpath same
  REACT_APP_ANALYTICS_BASE_URL: "{{ url.name.admin }}/analytics" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SERVICES_BASE_URL: "{{ url.name.admin }}/services" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SETTINGS_BASE_URL: "{{ url.name.admin }}/settings" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MONITORING_BASE_URL: "{{ url.name.admin }}/monitoring" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SERVICE_ID: "conversations,settings,monitoring"
  REACT_APP_NOTIFICATION_NODE_URL: "{{ url.name.ruuter }}" # Change the domain name, leave subdomain and subpath same


liquibase:
  jdbcUrl: "jdbc:postgresql://component-databases-users-db:5432/byk?user=byk"    
  dbPassword: "{{ usersDB.password }}"   # Change password accordingly
