imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


domain: {{ domain.name }} # Domain name
secretname: {{ admin.cert.Name.value }} # Cert name value, change this as suited to environment

ingress:
  certIssuerName: {{ cert.Issuer.Name }} # Change this if your certIssuerName has set up different
  whitelistSourceRange: "" # Client based IP if the whitelisting is needed, if not, leave as it is

release_name: "module-byk-backoffice-gui"


images:
  gui:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-chatbot"
    tag: "{{ module.backoffice.gui.version }}" # Images (tags) are up to date, currently no changes needed
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "{{ module.backoffice.image.version }}" # Images (tags) are up to date, currently no changes needed
  liquibase:
    dsl:
      repo: https://github.com/buerokratt/Buerokratt-Chatbot.git
      path: DSL/Liquibase

env:
  REACT_APP_RUUTER_API_URL: "{{ url.name.ruuter }}/v2/public/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_RUUTER_PRIVATE_API_URL: "{{ url.name.ruuter }}/v2/private/backoffice" # Change the domain name, leave subdomain and subpath same
  REACT_APP_BUEROKRATT_CHATBOT_URL: "{{ url.name.admin }}/chat" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MENU_URL: "{{ url.name.admin }}" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MENU_PATH: "/chat/menu.json"
  REACT_APP_CUSTOMER_SERVICE_LOGIN: "{{ url.name.admin }}/et/log-in" # Change the domain name, leave subdomain and subpath same
  DOMAIN: "{{ domain.name }}"
  REACT_APP_CONVERSATIONS_BASE_URL: "{{ url.name.admin }}/chat" # Change the domain name, leave subdomain and subpath same
  REACT_APP_TRAINING_BASE_URL: "{{ url.name.admin }}/training" # Change the domain name, leave subdomain and subpath same
  REACT_APP_ANALYTICS_BASE_URL: "{{ url.name.admin }}/analytics" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SERVICES_BASE_URL: "{{ url.name.admin }}/services" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SETTINGS_BASE_URL: "{{ url.name.admin }}/settings" # Change the domain name, leave subdomain and subpath same
  REACT_APP_MONITORING_BASE_URL: "{{ url.name.admin }}/monitoring" # Change the domain name, leave subdomain and subpath same
  REACT_APP_SERVICE_ID: "conversations,settings,monitoring"
  REACT_APP_NOTIFICATION_NODE_URL: "{{ url.name.ruuter }}" # Change the domain name, leave subdomain and subpath same
  REACT_APP_ENABLE_HIDDEN_FEATURES: "false"
  REACT_APP_VALIDATIONS_ENABLED: "FALSE"
  REACT_APP_MENU_JSON: "[{"id":"conversations","label":{"et":"Vestlused","en":"Conversations"},"path":"/chat","children":[{"label":{"et":"Vastamata","en":"Unanswered"},"path":"/unanswered"},{"label":{"et":"Aktiivsed","en":"Active"},"path":"/active"},{"label":{"et":"Ootel","en":"Pending"},"path":"/pending"},{"label":{"et":"Ajalugu","en":"History"},"path":"/history"}]},{"id":"training","label":{"et":"Treening","en":"Training"},"path":"/training","children":[{"label":{"et":"Treening","en":"Training"},"path":"/training","children":[{"label":{"et":"Teemad","en":"Themes"},"path":"/training/intents"},{"hidden":true,"label":{"et":"Avalikud teemad","en":"Public themes"},"path":"/training/common-intents"},{"label":{"et":"Teemade järeltreenimine","en":"Post training themes"},"path":"/training/intents-followup-training"},{"label":{"et":"Vastused","en":"Answers"},"path":"/training/responses"},{"label":{"et":"Reeglid","en":"Rules"},"path":"/training/rules"},{"label":{"et":"Konfiguratsioon","en":"Configuration"},"path":"/training/configuration"},{"label":{"et":"Vormid","en":"Forms"},"path":"/training/forms"},{"label":{"et":"Mälukohad","en":"Slots"},"path":"/training/slots"},{"label":{"et":"Automatic Teenused","en":"Automatic Services"},"path":"/auto-services"}]},{"label":{"et":"Ajaloolised vestlused","en":"Historical conversations"},"path":"/history","children":[{"label":{"et":"Ajalugu","en":"History"},"path":"/history/history"},{"label":{"et":"Pöördumised","en":"Appeals"},"path":"/history/appeal"}]},{"label":{"et":"Mudelipank ja analüütika","en":"Modelbank and analytics"},"path":"/analytics","children":[{"label":{"et":"Teemade ülevaade","en":"Overview of topics"},"path":"/analytics/overview"},{"label":{"et":"Mudelite võrdlus","en":"Comparison of models"},"path":"/analytics/models"},{"label":{"et":"Testlood","en":"testTracks"},"path":"/analytics/testcases"}]},{"label":{"et":"Treeni uus mudel","en":"Train new model"},"path":"/train-new-model"}]},{"id":"analytics","label":{"et":"Analüütika","en":"Analytics"},"path":"/analytics","children":[{"label":{"et":"Ülevaade","en":"Overview"},"path":"/overview"},{"label":{"et":"Vestlused","en":"Chats"},"path":"/chats"},{"label":{"et":"Tagasiside","en":"Feedback"},"path":"/feedback"},{"label":{"et":"Nõustajad","en":"Advisors"},"path":"/advisors"},{"label":{"et":"Avaandmed","en":"Reports"},"path":"/reports"}]},{"id":"services","label":{"et":"Teenused","en":"Services"},"path":"/services","children":[{"label":{"et":"Ülevaade","en":"Overview"},"path":"/overview"},{"label":{"et":"Uus teenus","en":"New Service"},"path":"/newService"},{"label":{"et":"Automatic Teenused","en":"Automatic Services"},"path":"/auto-services"},{"label":{"et":"Probleemsed teenused","en":"Faulty Services"},"path":"/faultyServices"}]},{"id":"settings","label":{"et":"Haldus","en":"Administration"},"path":"/settings","children":[{"label":{"et":"Kasutajad","en":"Users"},"path":"/users"},{"label":{"et":"Vestlusbot","en":"Chatbot"},"path":"/chatbot","children":[{"label":{"et":"Seaded","en":"Settings"},"path":"/chatbot/settings"},{"label":{"et":"Tervitussõnum","en":"Welcome message"},"path":"/chatbot/welcome-message"},{"label":{"et":"Välimus ja käitumine","en":"Appearance and behavior"},"path":"/chatbot/appearance"},{"label":{"et":"Erakorralised teated","en":"Emergency notices"},"path":"/chatbot/emergency-notices"}]},{"label":{"et":"Asutuse tööaeg","en":"Office opening hours"},"path":"/working-time"},{"label":{"et":"Vestluse Kustutamine","en":"Delete Conversations"},"path":"/delete-conversations"},{"label":{"et":"Sessiooni pikkus","en":"Session length"},"path":"/session-length"},{"label":{"et":"SKMi konfiguratsioon","en":"SKM Configuration"},"path":"/skm-configuration"}]},{"id":"monitoring","label":{"et":"Seire","en":"Monitoring"},"path":"/monitoring","children":[{"label":{"et":"Aktiivaeg","en":"Working hours"},"path":"/uptime"}]}]"
  RATE_LIMIT_PER_MINUTE: "1000"


liquibase:
  jdbcUrl: "jdbc:postgresql://component-databases-users-db:5432/byk?user=byk"    
  dbPassword: "{{ usersDB.password }}"   # Change password accordingly

resources:
  requests:
    memory: "10Mi"
    cpu: "1m"
  limits:
    memory: "50Mi"
    cpu: "5m"
