apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-service-secrets
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi  
