apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ namespace }}-commonservice
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi  
