imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicas: 1
podAnnotations: {}

podSecurityContext: {}

securityContext: {}

domain: {{ domain.name }} # Domain name


ingress:
  certIssuerName: {{ cert.Issuer.Name }}

release_name: "component-byk-xtr"  


images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/xtr"
    tag: "{{ component.xtr.image.version }}" # Images (tags) are up to date, currently no changes needed
xtr:
  xtr:
    repo: https://github.com/buerokratt/xtr.git
    path: DSL/

resources:
  requests:
    memory: "260Mi"
    cpu: "50m"
  limits:
    memory: "300Mi"
    cpu: "50m"
