apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:


      containers:
      - name: "{{ .Values.release_name }}"
        image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
        env:
        - name: RASA_MAX_CACHE_SIZE
          value: "0"
        command: ["/bin/sh"]
        args:
          - "-c"
          - >
            rasa run --enable-api
              
        ports:
        - containerPort: 5005
        volumeMounts:
          - name: bot-rasa-models
            mountPath: /app/models
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
      volumes:
      - name: bot-rasa-models
        persistentVolumeClaim:
          claimName: pvc-bot-models



