apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      initContainers:
        # - name: bring-loba-folder-for-init-train
        #   image: alpine/git:2.36.3
        #   volumeMounts:
        #   - name: rasa-training-data
        #     mountPath: /app
        # command: ["/bin/sh"]
        # args:
        #   - "-c"
        #   - >
        #     git clone $DSL_REPO /tmp/dsl-source &&
        #     echo 'downloaded' &&
        #     cp -r /tmp/dsl-source/$DSL_PATH/loba/* /app/ &&
        #     echo 'moved' &&
        #     adduser --no-create-home --disabled-password rasa &&
        #     chown -R rasa:rasa /app &&
        #     ls /app

        # env:
        #   - name: DSL_REPO
        #     value: {{ .Values.bot.dsl.repo }}
        #   - name: DSL_PATH
        #     value: {{ .Values.bot.dsl.path }}

      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
          env:
            - name: RASA_MAX_CACHE_SIZE
              value: "0"
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              rasa run --enable-api

          ports:
            - containerPort: 5005
          volumeMounts:
            - name: bot-rasa-models
              mountPath: /app/models
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: bot-rasa-models
          persistentVolumeClaim:
            claimName: pvc-bot-models
