apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      initContainers:
        - name: init-copy-files
          image: "{{ .Values.images.dsl.registry }}/{{ .Values.images.dsl.repository }}:{{ .Values.images.dsl.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              pwd
              cp -r ../Ruuter/ /app/DSL
              cp -r ../Resql/ /app/DSL
              cp -r ../DataMapper/ /app/DSL
              cp -r ../OpenSearch/ /app/DSL
              cp -r ../Liquibase/ /app/DSL
              ls -la 
          volumeMounts:
            - name: training-dsl
              mountPath: /app/DSL
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.gui.registry }}/{{ .Values.images.gui.repository }}:{{ .Values.images.gui.tag }}"
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /app/.env.development
              subPath: env.development
            # - name: rasa-training-data
            #   mountPath: /api/data
          env:
            - name: REACT_APP_RUUTER_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_API_URL }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
            - name: CHOKIDAR_USEPOLLING
              value: "{{ .Values.env.CHOKIDAR_USEPOLLING }}"
            - name: REACT_APP_API_URL
              value: "{{ .Values.env.REACT_APP_API_URL }}"
            - name: REACT_APP_BUEROKRATT_CHATBOT_URL
              value: "{{ .Values.env.REACT_APP_BUEROKRATT_CHATBOT_URL }}"
            - name: REACT_APP_OPENSEARCH_DASHBOARD_URL
              value: "{{ .Values.env.REACT_APP_OPENSEARCH_DASHBOARD_URL }}"
            - name: REACT_APP_OPENDATAPORT_URL
              value: "{{ .Values.env.REACT_APP_OPENDATAPORT_URL }}"
            - name: REACT_APP_RUUTER_V2_PRIVATE_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_V2_PRIVATE_API_URL }}"
            - name: REACT_APP_RUUTER_V2_ANALYTICS_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_V2_ANALYTICS_API_URL }}"
            - name: REACT_APP_MENU_URL
              value: "{{ .Values.env.REACT_APP_MENU_URL }}"
            - name: REACT_APP_MENU_PATH
              value: "{{ .Values.env.REACT_APP_MENU_PATH }}"
            - name: REACT_APP_AUTH_BASE_URL
              value: "{{ .Values.env.REACT_APP_AUTH_BASE_URL }}"
            - name: REACT_APP_APP_PORT
              value: "{{ .Values.env.REACT_APP_APP_PORT }}"
            - name: REACT_APP_LOCAL
              value: "{{ .Values.env.REACT_APP_LOCAL }}"
            - name: REACT_APP_DOCKER_RUUTER
              value: "{{ .Values.env.REACT_APP_DOCKER_RUUTER }}"
            - name: REACT_APP_CUSTOMER_SERVICE_LOGIN
              value: "{{ .Values.env.REACT_APP_CUSTOMER_SERVICE_LOGIN }}"
            - name: REACT_APP_CONVERSATIONS_BASE_URL
              value: "{{ .Values.env.REACT_APP_CONVERSATIONS_BASE_URL }}"
            - name: REACT_APP_TRAINING_BASE_URL
              value: "{{ .Values.env.REACT_APP_TRAINING_BASE_URL }}"
            - name: REACT_APP_ANALYTICS_BASE_URL
              value: "{{ .Values.env.REACT_APP_ANALYTICS_BASE_URL }}"
            - name: REACT_APP_SERVICES_BASE_URL
              value: "{{ .Values.env.REACT_APP_SERVICES_BASE_URL }}"
            - name: REACT_APP_SETTINGS_BASE_URL
              value: "{{ .Values.env.REACT_APP_SETTINGS_BASE_URL }}"
            - name: REACT_APP_MONITORING_BASE_URL
              value: "{{ .Values.env.REACT_APP_MONITORING_BASE_URL }}"
            - name: REACT_APP_SERVICE_ID
              value: "{{ .Values.env.REACT_APP_SERVICE_ID }}"
            - name: REACT_APP_RUUTER_PRIVATE_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_PRIVATE_API_URL }}"
            - name: REACT_APP_BASE_URL
              value: "{{ .Values.env.REACT_APP_BASE_URL }}"
            - name: REACT_APP_SERVICE_MODULE_GUI_BASE_URL
              value: "{{ .Values.env.REACT_APP_SERVICE_MODULE_GUI_BASE_URL }}"
            - name: REACT_APP_NODE_ENV
              value: "{{ .Values.env.REACT_APP_NODE_ENV }}"
            - name: REACT_APP_RUUTER_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_URL }}"
            - name: REACT_APP_PUBLIC_URL
              value: "{{ .Values.env.REACT_APP_PUBLIC_URL }}"
            - name: REACT_APP_ENABLE_HIDDEN_FEATURES
              value: "FALSE"
# For test
#            - name: REACT_APP_MENU_JSON
#              value: "[{\"id\":\"conversations\",\"label\":{\"et\":\"Vestlused\",\"en\":\"Conversations\"},\"path\":\"/chat\",\"children\":[{\"label\":{\"et\":\"Vastamata\",\"en\":\"Unanswered\"},\"path\":\"/unanswered\"},{\"label\":{\"et\":\"Aktiivsed\",\"en\":\"Active\"},\"path\":\"/active\"},{\"label\":{\"et\":\"Ajalugu\",\"en\":\"History\"},\"path\":\"/history\"},{\"label\":{\"et\":\"Ootel\",\"en\":\"Pending\"},\"path\":\"/pending\"}]},{\"id\":\"training\",\"label\":{\"et\":\"Treening\",\"en\":\"Training\"},\"path\":\"/training\",\"children\":[{\"label\":{\"et\":\"Treening\",\"en\":\"Training\"},\"path\":\"/training\",\"children\":[{\"label\":{\"et\":\"Teemad\",\"en\":\"Themes\"},\"path\":\"/training/intents\"},{\"label\":{\"et\":\"Avalikud teemad\",\"en\":\"Public themes\"},\"path\":\"/training/common-intents\"},{\"label\":{\"et\":\"Teemade järeltreenimine\",\"en\":\"Post training themes\"},\"path\":\"/training/intents-followup-training\"},{\"label\":{\"et\":\"Vastused\",\"en\":\"Answers\"},\"path\":\"/training/responses\"},{\"label\":{\"et\":\"Kasutuslood\",\"en\":\"User Stories\"},\"path\":\"/training/stories\"},{\"label\":{\"et\":\"Konfiguratsioon\",\"en\":\"Configuration\"},\"path\":\"/training/configuration\"},{\"label\":{\"et\":\"Vormid\",\"en\":\"Forms\"},\"path\":\"/training/forms\"},{\"label\":{\"et\":\"Mälukohad\",\"en\":\"Slots\"},\"path\":\"/training/slots\"},{\"label\":{\"et\":\"Automatic Teenused\",\"en\":\"Automatic Services\"},\"path\":\"/auto-services\"}]},{\"label\":{\"et\":\"Ajaloolised vestlused\",\"en\":\"Historical conversations\"},\"path\":\"/history\",\"children\":[{\"label\":{\"et\":\"Ajalugu\",\"en\":\"History\"},\"path\":\"/history/history\"},{\"label\":{\"et\":\"Pöördumised\",\"en\":\"Appeals\"},\"path\":\"/history/appeal\"}]},{\"label\":{\"et\":\"Mudelipank ja analüütika\",\"en\":\"Modelbank and analytics\"},\"path\":\"/analytics\",\"children\":[{\"label\":{\"et\":\"Teemade ülevaade\",\"en\":\"Overview of topics\"},\"path\":\"/analytics/overview\"},{\"label\":{\"et\":\"Mudelite võrdlus\",\"en\":\"Comparison of models\"},\"path\":\"/analytics/models\"},{\"label\":{\"et\":\"Testlood\",\"en\":\"testTracks\"},\"path\":\"/analytics/testcases\"}]},{\"label\":{\"et\":\"Treeni uus mudel\",\"en\":\"Train new model\"},\"path\":\"/train-new-model\"}]},{\"id\":\"analytics\",\"label\":{\"et\":\"Analüütika\",\"en\":\"Analytics\"},\"path\":\"/analytics\",\"children\":[{\"label\":{\"et\":\"Ülevaade\",\"en\":\"Overview\"},\"path\":\"/overview\"},{\"label\":{\"et\":\"Vestlused\",\"en\":\"Chats\"},\"path\":\"/chats\"},{\"label\":{\"et\":\"Bürokratt\",\"en\":\"Burokratt\"},\"path\":\"/burokratt\"},{\"label\":{\"et\":\"Tagasiside\",\"en\":\"Feedback\"},\"path\":\"/feedback\"},{\"label\":{\"et\":\"Nõustajad\",\"en\":\"Advisors\"},\"path\":\"/advisors\"},{\"label\":{\"et\":\"Avaandmed\",\"en\":\"Reports\"},\"path\":\"/reports\"}]},{\"id\":\"services\",\"label\":{\"et\":\"Teenused\",\"en\":\"Services\"},\"path\":\"/services\",\"children\":[{\"label\":{\"et\":\"Ülevaade\",\"en\":\"Overview\"},\"path\":\"/overview\"},{\"label\":{\"et\":\"Uus teenus\",\"en\":\"New Service\"},\"path\":\"/newService\"},{\"label\":{\"et\":\"Automatic Teenused\",\"en\":\"Automatic Services\"},\"path\":\"/auto-services\"},{\"label\":{\"et\":\"Probleemsed teenused\",\"en\":\"Faulty Services\"},\"path\":\"/faultyServices\"}]},{\"id\":\"settings\",\"label\":{\"et\":\"Haldus\",\"en\":\"Administration\"},\"path\":\"/settings\",\"children\":[{\"label\":{\"et\":\"Kasutajad\",\"en\":\"Users\"},\"path\":\"/users\"},{\"label\":{\"et\":\"Vestlusbot\",\"en\":\"Chatbot\"},\"path\":\"/chatbot\",\"children\":[{\"label\":{\"et\":\"Seaded\",\"en\":\"Settings\"},\"path\":\"/chatbot/settings\"},{\"label\":{\"et\":\"Tervitussõnum\",\"en\":\"Welcome message\"},\"path\":\"/chatbot/welcome-message\"},{\"label\":{\"et\":\"Välimus ja käitumine\",\"en\":\"Appearance and behavior\"},\"path\":\"/chatbot/appearance\"},{\"label\":{\"et\":\"Erakorralised teated\",\"en\":\"Emergency notices\"},\"path\":\"/chatbot/emergency-notices\"}]},{\"label\":{\"et\":\"Asutuse tööaeg\",\"en\":\"Office opening hours\"},\"path\":\"/working-time\"},{\"label\":{\"et\":\"Sessiooni pikkus\",\"en\":\"Session length\"},\"path\":\"/session-length\"}]},{\"id\":\"monitoring\",\"label\":{\"et\":\"Seire\",\"en\":\"Monitoring\"},\"path\":\"/monitoring\",\"children\":[{\"label\":{\"et\":\"Aktiivaeg\",\"en\":\"Working hours\"},\"path\":\"/uptime\"}]}]"
# For prod
            - name: REACT_APP_MENU_JSON
              value: "[{\"id\":\"conversations\",\"label\":{\"et\":\"Vestlused\",\"en\":\"Conversations\"},\"path\":\"/chat\",\"children\":[{\"label\":{\"et\":\"Vastamata\",\"en\":\"Unanswered\"},\"path\":\"/unanswered\"},{\"label\":{\"et\":\"Aktiivsed\",\"en\":\"Active\"},\"path\":\"/active\"},{\"label\":{\"et\":\"Ootel\",\"en\":\"Pending\"},\"path\":\"/pending\"},{\"label\":{\"et\":\"Ajalugu\",\"en\":\"History\"},\"path\":\"/history\"}]},{\"id\":\"training\",\"label\":{\"et\":\"Treening\",\"en\":\"Training\"},\"path\":\"/training\",\"children\":[{\"label\":{\"et\":\"Treening\",\"en\":\"Training\"},\"path\":\"/training\",\"children\":[{\"label\":{\"et\":\"Teemad\",\"en\":\"Themes\"},\"path\":\"/training/intents\"},{\"hidden\":true,\"label\":{\"et\":\"Avalikud teemad\",\"en\":\"Public themes\"},\"path\":\"/training/common-intents\"},{\"hidden\":true,\"label\":{\"et\":\"Teemade järeltreenimine\",\"en\":\"Post training themes\"},\"path\":\"/training/intents-followup-training\"},{\"label\":{\"et\":\"Vastused\",\"en\":\"Answers\"},\"path\":\"/training/responses\"},{\"label\":{\"et\":\"Reeglid\",\"en\":\"User Stories\"},\"path\":\"/training/stories\"},{\"hidden\":true,\"label\":{\"et\":\"Konfiguratsioon\",\"en\":\"Configuration\"},\"path\":\"/training/configuration\"},{\"hidden\":true,\"label\":{\"et\":\"Vormid\",\"en\":\"Forms\"},\"path\":\"/training/forms\"},{\"hidden\":true,\"label\":{\"et\":\"Mälukohad\",\"en\":\"Slots\"},\"path\":\"/training/slots\"},{\"hidden\":true,\"label\":{\"et\":\"Automatic Teenused\",\"en\":\"Automatic Services\"},\"path\":\"/auto-services\"}]},{\"label\":{\"et\":\"Ajaloolised vestlused\",\"en\":\"Historical conversations\"},\"path\":\"/history\",\"children\":[{\"label\":{\"et\":\"Ajalugu\",\"en\":\"History\"},\"path\":\"/history/history\"},{\"hidden\":true,\"label\":{\"et\":\"Pöördumised\",\"en\":\"Appeals\"},\"path\":\"/history/appeal\"}]},{\"label\":{\"et\":\"Mudelipank ja analüütika\",\"en\":\"Modelbank and analytics\"},\"path\":\"/analytics\",\"children\":[{\"label\":{\"et\":\"Teemade ülevaade\",\"en\":\"Overview of topics\"},\"path\":\"/analytics/overview\"},{\"label\":{\"et\":\"Mudelite võrdlus\",\"en\":\"Comparison of models\"},\"path\":\"/analytics/models\"},{\"hidden\":true,\"label\":{\"et\":\"Testlood\",\"en\":\"testTracks\"},\"path\":\"/analytics/testcases\"}]},{\"label\":{\"et\":\"Treeni uus mudel\",\"en\":\"Train new model\"},\"path\":\"/train-new-model\"}]},{\"id\":\"analytics\",\"label\":{\"et\":\"Analüütika\",\"en\":\"Analytics\"},\"path\":\"/analytics\",\"children\":[{\"label\":{\"et\":\"Ülevaade\",\"en\":\"Overview\"},\"path\":\"/overview\"},{\"label\":{\"et\":\"Vestlused\",\"en\":\"Chats\"},\"path\":\"/chats\"},{\"label\":{\"et\":\"Tagasiside\",\"en\":\"Feedback\"},\"path\":\"/feedback\"},{\"label\":{\"et\":\"Nõustajad\",\"en\":\"Advisors\"},\"path\":\"/advisors\"},{\"hidden\":true,\"label\":{\"et\":\"Avaandmed\",\"en\":\"Reports\"},\"path\":\"/reports\"}]},{\"id\":\"services\",\"hidden\":true,\"label\":{\"et\":\"Teenused\",\"en\":\"Services\"},\"path\":\"/services\",\"children\":[{\"label\":{\"et\":\"Ülevaade\",\"en\":\"Overview\"},\"path\":\"/overview\"},{\"label\":{\"et\":\"Uus teenus\",\"en\":\"New Service\"},\"path\":\"/newService\"},{\"label\":{\"et\":\"Automatic Teenused\",\"en\":\"Automatic Services\"},\"path\":\"/auto-services\"},{\"label\":{\"et\":\"Probleemsed teenused\",\"en\":\"Faulty Services\"},\"path\":\"/faultyServices\"}]},{\"id\":\"settings\",\"label\":{\"et\":\"Haldus\",\"en\":\"Administration\"},\"path\":\"/settings\",\"children\":[{\"label\":{\"et\":\"Kasutajad\",\"en\":\"Users\"},\"path\":\"/users\"},{\"label\":{\"et\":\"Vestlusbot\",\"en\":\"Chatbot\"},\"path\":\"/chatbot\",\"children\":[{\"label\":{\"et\":\"Seaded\",\"en\":\"Settings\"},\"path\":\"/chatbot/settings\"},{\"label\":{\"et\":\"Tervitussõnum\",\"en\":\"Welcome message\"},\"path\":\"/chatbot/welcome-message\"},{\"label\":{\"et\":\"Välimus ja käitumine\",\"en\":\"Appearance and behavior\"},\"path\":\"/chatbot/appearance\"},{\"label\":{\"et\":\"Erakorralised teated\",\"en\":\"Emergency notices\"},\"path\":\"/chatbot/emergency-notices\"}]},{\"label\":{\"et\":\"Asutuse tööaeg\",\"en\":\"Office opening hours\"},\"path\":\"/working-time\"},{\"label\":{\"et\":\"Sessiooni pikkus\",\"en\":\"Session length\"},\"path\":\"/session-length\"}]},{\"id\":\"monitoring\",\"hidden\":true,\"label\":{\"et\":\"Seire\",\"en\":\"Monitoring\"},\"path\":\"/monitoring\",\"children\":[{\"label\":{\"et\":\"Aktiivaeg\",\"en\":\"Working hours\"},\"path\":\"/uptime\"}]}]"
          livenessProbe:
            httpGet:
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
        - name: "{{ .Values.release_name }}-pipelines"
          image: "{{ .Values.images.pipelines.registry }}/{{ .Values.images.pipelines.repository }}:{{ .Values.images.pipelines.tag }}"
          ports:
            - containerPort: 3010
          env:
            - name: OPENSEARCH_PROTOCOL
              value: "http"
            - name: OPENSEARCH_HOST
              value: "component-opensearch-node"
            - name: OPENSEARCH_PORT
              value: "9200"
            - name: OPENSEARCH_AUTH
              value: "admin:admin"
          resources:
            requests:
              memory: "{{ .Values.resources.pipeline.requests.memory }}"
              cpu: "{{ .Values.resources.pipeline.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.pipeline.limits.memory }}"
              cpu: "{{ .Values.resources.pipeline.limits.cpu }}"
      volumes:
        - name: config-volume
          configMap:
            name: configmap-byk-training
        - name: training-dsl
          persistentVolumeClaim:
            claimName: pvc-{{ namespace }}-training-dsl
        # - name: rasa-training-data
        #   persistentVolumeClaim:
        #     claimName: rasa-training-data

