apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ namespace }}-training-dsl
spec:
  storageClassName: dsl
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/training-dsl
