apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ namespace }}-training-dsl
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
