apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: byk-{{ namespace }}-dsl-training
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  
