apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
          ports:
            - containerPort: 4040
          env:
            - name: OPENSEARCH_PROTOCOL
              value: "{{ .Values.env.OPENSEARCH_PROTOCOL }}"
            - name: OPENSEARCH_HOST
              value: "{{ .Values.env.OPENSEARCH_HOST }}"
            - name: OPENSEARCH_PORT
              value: "{{ .Values.env.OPENSEARCH_PORT }}"
            - name: OPENSEARCH_USERNAME
              value: "{{ .Values.env.OPENSEARCH_USERNAME }}"
            - name: OPENSEARCH_PASSWORD
              value: "{{ .Values.env.OPENSEARCH_PASSWORD }}"
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: REFRESH_INTERVAL
              value: "{{ .Values.env.REFRESH_INTERVAL }}"
            - name: CORS_WHITELIST_ORIGINS
              value: "{{ .Values.env.CORS_WHITELIST_ORIGINS }}"
            - name: RUUTER_URL
              value: "{{ .Values.env.RUUTER_URL }}"
            - name: CHAT_TERMINATION_DELAY
              value: "{{ .Values.env.CHAT_TERMINATION_DELAY }}"
            - name: AZURE_OPENAI_ENDPOINT
              value: "{{ .Values.env.AZURE_OPENAI_ENDPOINT }}"
            - name: AZURE_OPENAI_API_KEY
              value: "{{ .Values.env.AZURE_OPENAI_API_KEY }}"
            - name: AZURE_OPENAI_DEPLOYMENT
              value: "{{ .Values.env.AZURE_OPENAI_DEPLOYMENT }}"
            - name: AZURE_OPENAI_API_VERSION
              value: "{{ .Values.env.AZURE_OPENAI_API_VERSION }}"
            - name: AZURE_OPENAI_MODEL
              value: "{{ .Values.env.AZURE_OPENAI_MODEL }}"
            - name: PRIVATE_RUUTER_URL
              value: "{{ .Values.env.PRIVATE_RUUTER_URL }}"
            - name: TERMINATION_TIMEOUT
              value: "{{ .Values.env.TERMINATION_TIMEOUT }}"
            - name: AZURE_TENANT_ID
              value: "{{ .Values.env.AZURE_TENANT_ID }}"
            - name: AZURE_GRANT_TYPE
              value: "{{ .Values.env.AZURE_GRANT_TYPE }}"
            - name: AZURE_SCOPE
              value: "{{ .Values.env.AZURE_SCOPE }}"
            - name: AZURE_AGENTIC_ENDPOINT
              value: "{{ .Values.env.AZURE_AGENTIC_ENDPOINT }}"
            - name: AZURE_AGENTIC_PROJECT_NAME
              value: "{{ .Values.env.AZURE_AGENTIC_PROJECT_NAME }}"
            - name: AZURE_AGENTIC_API_VERSION
              value: "{{ .Values.env.AZURE_AGENTIC_API_VERSION }}"
              
          volumeMounts:
            - name: notification-server
              mountPath: /app/notification-server
          # livenessProbe:
          #   httpGet:
          #     port: 4040
          #   initialDelaySeconds: 26
          #   periodSeconds: 11
          # readinessProbe:
          #   httpGet:
          #     port: 4040
          #   initialDelaySeconds: 25
          #   periodSeconds: 10
      volumes:
        - name: notification-server
          emptyDir: {}
      initContainers:
        - name: clone-repo
          image: alpine/git
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              git clone --branch main --single-branch https://github.com/buerokratt/Buerokratt-Chatbot.git /app/Buerokratt-Chatbot && \
              cp -r /app/Buerokratt-Chatbot/notification-server/* /app/notification-server/
          volumeMounts:
            - name: notification-server
              mountPath: /app/notification-server 
