nameOverride: component-byk-resql
fullnameOverride: component-byk-resql
replicaCount: 1
podAnnotations: {}
workload:
  kind: Deployment
  selectorLabels: {app: component-byk-resql}
istio:
  enabled: false
image:
  repository: ghcr.io
  name: buerokratt/resql
  tag: "{{ component.resql.image.version }}"
  pullPolicy: IfNotPresent
initContainers:
  - name: init-copy-files-backoffice
    image: "ghcr.io/buerokratt/buerokratt-dsl:{{ module.backoffice.image.version }}"
    command: ["/bin/sh", "-c"]
    args: ["pwd; cp -r ../Resql/backoffice/ /root/DSL/; ls -la /root/DSL/"]
    volumeMounts: [{name: resql-volume, mountPath: /root/DSL/}]
  - name: init-copy-files-analytics
    image: "ghcr.io/buerokratt/buerokratt-dsl:{{ module.analytics.image.version }}"
    command: ["/bin/sh", "-c"]
    args: ["pwd; cp -r ../Resql/analytics /root/DSL/; ls -la /root/DSL/"]
    volumeMounts: [{name: resql-volume, mountPath: /root/DSL/}]
  - name: init-copy-files-training
    image: "ghcr.io/buerokratt/buerokratt-dsl:{{ module.training.image.version }}"
    command: ["/bin/sh", "-c"]
    args: ["pwd; cp -r ../Resql/training /root/DSL/; ls -la /root/DSL/"]
    volumeMounts: [{name: resql-volume, mountPath: /root/DSL/}]
  - name: init-copy-files-services
    image: "ghcr.io/buerokratt/buerokratt-dsl:{{ module.services.image.version }}"
    command: ["/bin/sh", "-c"]
    args: ["pwd; cp -r ../Resql/services /root/DSL/; ls -la /root/DSL/"]
    volumeMounts: [{name: resql-volume, mountPath: /root/DSL/}]
containerPorts:
  - {name: http, containerPort: 8082}
startupProbe:
  tcpSocket: {port: 8082}
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 24
  successThreshold: 1
readinessProbe:
  tcpSocket: {port: 8082}
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1
livenessProbe:
  tcpSocket: {port: 8082}
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1
env:
  - {name: logging.level.root, value: INFO}
  - {name: SQLMS_DATASOURCES_0_NAME, value: byk}
  - {name: SQLMS_DATASOURCES_0_JDBCURL, value: "jdbc:postgresql://component-databases-users-db:5432/byk"}
  - {name: SQLMS_DATASOURCES_0_USERNAME, value: byk}
  - {name: SQLMS_DATASOURCES_0_PASSWORD, value: CHANGE_ME}
  - {name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT, value: DEBUG}
  - {name: SQLMS_SAVED_QUERIES_DIR, value: /DSL/}
resources:
  requests: {memory: 1000Mi}
  limits: {memory: 2000Mi}
volumeMounts:
  - {name: resql-volume, mountPath: /DSL/}
volumes:
  - name: resql-volume
    emptyDir: {}
services:
  http:
    name: component-byk-resql
    ports:
      http: {port: 8082, targetPort: http}
