imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicas: 1
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: {{ domain.name }} # Domain name
#secretname: {{ cert.Name.value }} # Cert name value, change this as suited to environment
#ingress:
#  certIssuerName: {{ cert.Issuer.Name }}  # Change this if your certIssuerName has set up different

release_name: "component-byk-s3"    

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/s3-ferry"
    tag: "{{ component.s3.ferry.image.version }}" # Images (tags) are up to date, currently no changes needed


env:
  S3_ENDPOINT_URL: {{ S3_ENDPOINT_URL }}

config:
  API_CORS_ORIGIN: "*"
  API_DOCUMENTATION_ENABLED: "true"
  S3_REGION: "{{ S3_REGION }}"
  S3_ENDPOINT_URL: "https://{{ S3_ENDPOINT_URL }}"
  S3_ACCESS_KEY_ID: "{{ S3_ACCESS_KEY_ID }}"
  S3_SECRET_ACCESS_KEY: "{{ S3_SECRET_ACCESS_KEY }}"
  S3_DATA_BUCKET_NAME: "{{ S3_DATA_BUCKET_NAME }}"
  S3_DATA_BUCKET_PATH: "{{ S3_DATA_BUCKET_PATH }}"
  FS_DATA_DIRECTORY_PATH: "./data"

resources:
  requests:
    memory: "60Mi"
    cpu: "20m"
  limits:
    memory: "100Mi"
    cpu: "20m"