map $remote_addr $is_allowed {
    default 0;
    127.0.0.1 1;
}

server {
    server_name localhost;
    listen 8090;

    server_tokens off;
    add_header Access-Control-Allow-Origin *;

    location /status {
      access_log off;
      default_type text/plain;
      add_header Content-Type text/plain;
      return 200 "alive";
    }

    location /testing {
        if ($is_allowed = 0) {
          return 403 'unauthorized'; 
        }

        proxy_pass http://ruuter:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
