apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
  annotations:
  sidecar.istio.io/inject: "{{ .Valus.istio.enabled }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      initContainers:
        - name: bring-common-service
          image: alpine/git:2.36.3
          volumeMounts:
            - name: cron-commonservice
              mountPath: /app/services
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              git clone $DSL_REPO /tmp/dsl-source &&
              echo 'downloaded' &&
              
              cp -r /tmp/dsl-source/$DSL_PATH/* /app/services &&
              echo 'moved' &&
              chmod 777 -R /app/services &&
              ls /app/services/              
          env:
            - name: DSL_REPO
              value: {{ .Values.images.commonservice.dsl.repo }}
            - name: DSL_PATH
              value: {{ .Values.images.commonservice.dsl.path }}
        - name: init-copy-cron-files
          image: "{{ .Values.images.cron.registry }}/{{ .Values.images.cron.repository }}:{{ .Values.images.cron.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              pwd
              cp -r ../DSL /shared-data
              ls -la 
          volumeMounts:
            - name: shared-cron-volume
              mountPath: /cron-data/    
        - name: cron-dsl-symlink
          image: busybox
          securityContext:
            runAsUser: 0     
            runAsGroup: 0                    
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Log directory permissions before attempting changes
              echo "Initial permissions for /cron-data:"
              ls -ld /cron-data
              
              # Try to change ownership and permissions
              echo "Attempting to change ownership and permissions..."
              chown -R 1000:1000 /cron-data || echo "Failed to change ownership"
              chmod -R 777 /cron-data/DSL || echo "Failed to change permissions"
              
              # Log directory permissions after changes
              echo "Permissions for /cron-data after attempting change:"
              ls -ld /cron-data/DSL

              # Create symlink
              ln -s /cron-data/DSL/* /DSL/
          volumeMounts:
            - name: cron-dsl
              mountPath: /DSL/
            - name: shared-cron-volume
              mountPath: /cron-data/
      containers:
      - name: "{{ .Values.release_name }}"
        image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
        ports:
        - containerPort: 9010
        env:
        - name: TRAINING_PUBLIC_RUUTER
          value: "{{ .Values.contstants.TRAINING_PUBLIC_RUUTER }}"
        - name: TRAINING_DMAPPER
          value: "{{ .Values.contstants.TRAINING_DMAPPER }}"
        - name: TRAINING_OPENSEARCH
          value: "{{ .Values.contstants.TRAINING_OPENSEARCH }}"
        - name: TRAINING_TIM
          value: "{{ .Values.contstants.TRAINING_TIM }}"
        - name: TRAINING_RESQL
          value: "{{ .Values.contstants.TRAINING_RESQL }}"
        - name: TRAINING_USERS_RESQL
          value: "{{ .Values.contstants.TRAINING_USERS_RESQL }}"
        - name: TRAINING_PIPELINE
          value: "{{ .Values.contstants.TRAINING_PIPELINE }}"
        - name: TRAINING_RASA
          value: "{{ .Values.contstants.TRAINING_RASA }}"
        - name: S3_FERRY
          value: "{{ .Values.contstants.S3_FERRY }}"
        - name: SERVICES_RESQL
          value: "{{ .Values.contstants.SERVICES_RESQL }}"
        - name: CRON_INSTANCE
          value: "{{ .Values.contstants.CRON_INSTANCE }}"
        - name: CRON_MANAGER
          value: "{{ .Values.contstants.CRON_MANAGER }}"
        - name: TRAINING_FILES_PATH
          value: "{{ .Values.contstants.TRAINING_FILES_PATH }}"
        - name: TESTING_FILES_PATH
          value: "{{ .Values.contstants.TESTING_FILES_PATH }}"
        - name: CROSS_VALIDATION_FILES_PATH
          value: "{{ .Values.contstants.CROSS_VALIDATION_FILES_PATH }}"
        - name: CHATBOT_BOT
          value: "{{ .Values.contstants.CHATBOT_BOT }}"
      resources:
        requests:
          memory: "{{ .Values.resources.requests.memory }}"
          cpu: "{{ .Values.resources.requests.cpu }}"
        limits:
          memory: "{{ .Values.resources.limits.memory }}"
          cpu: "{{ .Values.resources.limits.cpu }}"
      livenessProbe:
        httpGet:
          port: 8080
        initialDelaySeconds: 360
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          port: 8080
        initialDelaySeconds: 360
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        volumeMounts:
        - name: trainbot-rasa-models
          mountPath: /data
        - name: cron-commonservice
          mountPath: /app/services
        - name: cronconst
          mountPath: /app/constants.ini
          subPath: constants.ini
        - name: shared-cron-volume
          mountPath: /cron-data/
        - name: cron-dsl
          mountPath: /DSL
      volumes:
      - name: cron-dsl
        emptyDir: {}
      - name: shared-cron-volume
        persistentVolumeClaim:
          claimName: cron-pvc 
      - name: trainbot-rasa-models
        persistentVolumeClaim:
          claimName: pvc-trainbot-models
      - name: cronconst
        configMap:
          name: cronconst
      - name: cron-commonservice
        emptyDir: {}
