imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: {{ domain.name }} # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

#release_name: "postdeploy"
release_name: "job-postdeploy-seed"
releaseName: post-deploy-pipeline-seed

dslRepo: "https://github.com/buerokratt/Training-Module.git"
dslPath: "/"
dslBranch: "dev"


images:
  scope:
    image: opensearchproject/opensearch:latest
  pipelines:
    training:
      repo: https://github.com/buerokratt/Training-Module.git
      path: /
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "{{ module.training.image.version }}" # Images (tags) are up to date, currently no changes needed

liquibase:
  jdbcUrl: "jdbc:postgresql://databases-users-db:5432/byk?user=byk"    
  dbPassword: "{{ usersDB.password }}"   # Change password accordingly