apiVersion: v2
name: datamapper
description: A Helm chart for Datamapper
type: application

version: 0.2.4
appVersion: 2.0.0

dependencies:
  - name: byk-helm-template-library
    version: 1.0.0
    repository: oci://ghcr.io/buerokratt
