
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicas: 1
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

istio:
  enabled: {{ istio.enabled }}

domain: {{ domain.name }} # Domain name

ingress:
  certIssuerName: {{ cert.Issuer.Name }} # Change this if your certIssuerName has set up different

release_name: "component-byk-dmapper"
      

images:
  scope:
    registry: "registry.gitlab.ria.ee"
    repository: byk/datamapper
    tag: {{ component.datamapper.image.version }}
  backoffice:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    tag: "{{ module.backoffice.image.version }}" # Images (tags) are up to date, currently no changes needed
  analytics:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    tag: "{{ module.analytics.image.version }}" # Images (tags) are up to date, currently no changes needed
  services:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    tag: "{{ module.services.image.version }}" # Images (tags) are up to date, currently no changes needed
  training:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    tag: "{{ module.training.image.version }}" # Images (tags) are up to date, currently no changes needed 
  s3ferry:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/s3-ferry"
    tag: "{{ component.s3.ferry.image.version }}" # Images (tags) are up to date, currently no changes needed
  pipelines:
    service:
      repo: https://gitlab.ria.ee/BYK/Service-Module.git
      path: /DSL
  bot:
    dsl:
      repo: https://gitlab.ria.ee/BYK/Training-Module.git
      path: DSL/DMapper/locations
  commonservice:
    dsl:
      repo: https://gitlab.ria.ee/BYK/Common-Services.git
      path: /
  sec:
    service:
      repo: https://gitlab.ria.ee/BYK/Service-Module.git
      path: /secrets

s3ferry:
  default:
    id: {{ S3_ACCESS_KEY_ID }}
    key: {{ S3_SECRET_ACCESS_KEY }}
    url: {{ S3_ENDPOINT_URL }}
  chats:
    id: {{ S3_ACCESS_KEY_ID }}
    key: S3_SECRET_ACCESS_KEY
    url: {{ S3_ENDPOINT_URL }}

resources:
  requests:
    memory: "1000Mi"
    cpu: "100m"
  limits:
    memory: "2000Mi"
    cpu: "100m"

networkPolicy:
  cidr: 0.0.0.0/0
  except: []

