apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox     # Using a lightweight container to execute permission commands
          command: ["sh", "-c"]
          args:
            - chown -R 1000:1000 /usr/share/opensearch/data && chmod -R 755 /usr/share/opensearch/data
          volumeMounts:
            - name: opensearch-{{ namespace }}-data
              mountPath: /usr/share/opensearch/data
      containers:
        - name: "{{ .Values.release_name }}"
          image: {{ .Values.images.scope.image }}
          env:
            - name: cluster.name
              value: "{{ .Values.env.CLUSTER_NAME }}"
            - name: node.name
              value: "{{ .Values.env.NODE_NAME }}"
            - name: discovery.type
              value: "{{ .Values.env.DISCOVERY_TYPE }}"
            - name: bootstrap.memory_lock
              value: "{{ .Values.env.BOOTSTRAP_MEMORY_LOCK }}"
            - name: OPENSEARCH_JAVA_OPTS
              value: "{{ .Values.env.OPENSEARCH_JAVA_OPTS }}"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "{{ .Values.env.DISABLE_INSTALL_DEMO_CONFIG }}"
            - name: DISABLE_SECURITY_PLUGIN
              value: "{{ .Values.env.DISABLE_SECURITY_PLUGIN }}"
            - name: node.max_local_storage_nodes
              value: "{{ nr_client }}"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9600
              name: opensearch
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 512Mi              
          volumeMounts:
            - name: opensearch-{{ namespace }}-data
              mountPath: /usr/share/opensearch/data
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          livenessProbe:
              httpGet:
                path: /_cluster/health
                port: 9200
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          readinessProbe:
              httpGet:
                path: /_cluster/health
                port: 9200
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
      volumes:
        - name: opensearch-{{ namespace }}-data
          persistentVolumeClaim:
            claimName: opensearch-{{ namespace }}-data  
