apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-{{ namespace }}-pv
spec:
  storageClassName: longhorn
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/opensearch
