apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-{{ namespace }}-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
