# tim secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-tim-secret
type: Opaque
stringData:
  password: "{{ TIMDB.password }}"
---
# loop for other databases
{{- range .Values.databases }}
{{- if ne .name "tim" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-secret
type: Opaque
stringData:
  password: "{{ .password }}"
---
{{- end }}
{{- end }}
