apiVersion: v1
kind: Service
metadata:
  name: {{ include "seaweedfs.fullname" . }}-s3
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "seaweedfs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: s3
  ports:
    - name: s3
      port: {{ .Values.s3.port }}
      targetPort: s3
