apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.release_name }}-seed"
  # annotations:
  #   "helm.sh/hook": post-install, post-upgrade
  #   "helm.sh/hook-weight": "1"
  #   "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      containers:
        - name: init-run-script
          image: curlimages/curl:7.79.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp /scripts/init_with_mocks.sh /tmp/init_with_mocks.sh
              chmod +x /tmp/init_with_mocks.sh
              ls -la /tmp
              cat /tmp/init_with_mocks.sh
              sh /tmp/init_with_mocks.sh http://module-byk-training-gui-pipelines:3010
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
            - name: trainbot-rasa-locations
              mountPath: /rasa/locations
            - name: temp-volume
              mountPath: /tmp
      volumes:
        - name: trainbot-rasa-locations
          persistentVolumeClaim:
            claimName: pvc-trainbot
        - name: script-volume
          configMap:
            name: init-script-config2
        - name: temp-volume
          emptyDir: {}
      restartPolicy: OnFailure
