release_name: "component-byk-dmapper"
domain: "example.com"
istio:
  enabled: false
images:
  scope:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/datamapper"
    # tag: "v1.0.0"
    tag: "latest"
  backoffice:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    # tag: "v1.0.0"
    tag: "latest"
  analytics:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    # tag: "v1.0.0"
    tag: "latest"
  services:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    # tag: "v1.0.0"
    tag: "latest"
  training:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    # tag: "v1.0.0"
    tag: "latest"

dslRepos:
  pipelines:
    repo: "https://gitlab.ria.ee/BYK/Service-Module.git"
    path: "/DSL"
  bot:
    repo: "https://gitlab.ria.ee/BYK/Training-Module.git"
    path: "DSL/DMapper/locations"
  commonservice:
    repo: "https://gitlab.ria.ee/BYK/Common-Services.git"
    path: "/"
  sec:
    repo: "https://gitlab.ria.ee/BYK/Service-Module.git"
    path: "/secrets"

resources:
  requests:
    memory: "1000Mi"
    cpu: "100m"
  limits:
    memory: "2000Mi"
    cpu: "100m"

replicas: 1
