nameOverride: module-byk-authentication-layer
fullnameOverride: module-byk-authentication-layer
replicaCount: 1

workload:
  kind: Deployment
  selectorLabels: {app: module-byk-authentication-layer}

image:
  repository: ghcr.io
  name: buerokratt/authentication-layer
  tag: "v1.1.2"
  pullPolicy: IfNotPresent

containerPorts:
  - {name: http, containerPort: 80}
  - {name: https, containerPort: 443}

env: []

resources:
  requests: {cpu: 1m, memory: 10Mi}
  limits: {cpu: 5m, memory: 50Mi}

services:
  http:
    name: module-byk-authentication-layer
    ports:
      http: {port: 80, targetPort: http, protocol: TCP}
      https: {port: 443, targetPort: https, protocol: TCP}

ingress: {enabled: false}
istio: {enabled: false}

defaultConf: |
  server {
    server_name localhost;
    listen 443;

    server_tokens off;
    add_header Content-Security-Policy "upgrade-insecure-requests; default-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' {{ url.name.ruuter }}/v2/public/ {{ url.name.tim }} {{ url.name.admin }} {{ url.name.ruuter }}/v2/private/;";

    location / {
      root /usr/share/nginx/html/customer-service;
      try_files $uri /index.html;
    }

    location /status {
      access_log off;
      default_type text/plain;
      add_header Content-Type text/plain;
      return 200 "alive";
    }
  }

  server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
  }

envConfigJs: |
  window._env_ = {
    "RUUTER_API_URL": "{{ url.name.ruuter }}/v2/public/backoffice",
    "TIM_API_URL": "{{ url.name.tim }}",
    "TARA_REDIRECT_URL": "{{ url.name.tim }}/oauth2/authorization/tara?callback_url={{ url.name.admin }}/auth/callback",
    "MONITORING_URL": "https://MONITORING_URL",
    "PASSWORD_AUTH_ENABLED": true,
    "BACKOFFICE_URL": "{{ url.name.admin }}/chat",
    "INSTITUTION_FORWARDING_ENABLED": true,
    "AUTHORITY_NAME": "BYK"
  };