databases:
  - name: tim
    username: tim
    password: "{{ TIMDB.password }}"
    db: tim
    storage: 1Gi
  - name: users-db
    username: byk
    password: "{{ usersDB.password }}"
    db: byk
    storage: 1Gi

image:
  repository: postgres
  tag: "14.1"
  pullPolicy: IfNotPresent

service:
  port: 5432

persistence:
  storageClass: longhorn
  accessModes: ["ReadWriteOnce"]
