domain: "test.buerokratt.ee"
secretname: "secretnamevaartus"
release_name: "module-byk-widget"

images:
  gui:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/chat-widget"
    # tag: "v1.1.1"
    tag: "latest"
  dsl:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/buerokratt-dsl"
    # tag: "v1.1.1"
    tag: "latest"

config: 
  header_origin: "https://test.buerokratt.ee"

resources:
  requests:
    memory: "10Mi"
    cpu: "1m"
  limits:
    memory: "50Mi"
    cpu: "5m"
