imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicas: 2
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: {{ domain.name }} # Domain name
secretname: {{ cert.Name.value }} # Cert name value, change this as suited to environment
ingress:
  certIssuerName: {{ cert.Issuer.Name }}  # Change this if your certIssuerName has set up different

istio:
  enabled: {{ istio.enabled }}

release_name: "component-byk-ruuter"    

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/ruuter"
    tag: "{{ component.ruuter.image.version }}" # Images (tags) are up to date, currently no changes needed
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "{{ module.backoffice.image.version }}" # Images (tags) are up to date, currently no changes needed

env:
  LOGGING_LEVEL_ROOT: "INFO"
  LOG_LEVEL_TIMING: "INFO"
  APPLICATION_LOGGING_DISPLAY_REQUEST_CONTENT: "false"
  APPLICATION_LOGGING_DISPLAY_RESPONSE_CONTENT: "false"
  APPLICATION_CORS_ALLOWED_ORIGINS: {{ url.name.admin }}, {{ url.name.domain }}, {{ url.name.tim }}, {{ url.name.ruuter }} # Change the domain name, leave subdomain and subpath same

resources:
  requests:
    memory: "385Mi"
    cpu: "256m"
  limits:
    memory: "512Mi"
    cpu: "512m"
