release_name: "ruuteritest"
domain: "eexample.com"
images:
  scope:
    registry: "registry.gitlab.ria.ee"
    repository: "byk/ruuter"
    # tag: "v2.2.3"
    tag: "latest"
secretname: "ruuter.stage.buerokratt.ee0001"
env:
  cors: "https://xample.com"
  sizelimit: "3000"
