apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      initContainers:
        - name: bring-xtr-data
          image: alpine/git:2.36.3
          volumeMounts:
            - name: xtr
              mountPath: /DSL
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              git clone $DSL_REPO /tmp/dsl-source &&
              echo 'downloaded' &&
              cp -r /tmp/dsl-source/$DSL_PATH/* /DSL &&
              echo 'moved'
          env:
            - name: DSL_REPO
              value: {{ .Values.xtr.xtr.repo }}
            - name: DSL_PATH
              value: {{ .Values.xtr.xtr.path }}
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: xtr
              mountPath: /DSL
      volumes:
        - name: xtr
          emptyDir: {}

