#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
public_ruuter=https://ruuter.test.buerokratt.ee
private_ruuter=https://priv-ruuter.test.buerokratt.ee
tim=https://tim.test.buerokratt.ee
widget=https://test.buerokratt.ee
back_office=https://admin.test.buerokratt.ee
username=ubuntu
safe_tim_db=           
safe_byk_db=          
buildpath="$(pwd)"
timdb=database-ip:5432 
taraid=               
tarapass=                                
keytoolCN=Test
keytoolOU=buerokratt
keytoolC=ee
keytoolpass=               
dburl=database-ip
bot_url=bot-ip:5005
training_url=training-ip
training_user=ubuntu
training_prv_key=/home/ubuntu/.ssh/id_rsa
training_bot_dir=chatbot
SSH_KEY=/home/ubuntu/.ssh/id_rsa
BOT_DATA_DIR=/home/bot-data
bot_name=test
