nameOverride: component-byk-cronmanager
fullnameOverride: component-byk-cronmanager
replicaCount: 1
 
workload:
  kind: Deployment
  selectorLabels: {app: component-byk-cronmanager}
podSecurityContext: {}

istio: {enabled: false}

image:
  repository: ghcr.io
  name: buerokratt/cronmanager
  tag: "{{ component.cronmanager.image.version }}"
  pullPolicy: IfNotPresent

startupProbe:
  httpGet:
    port: http
    path: /healthz
  periodSeconds: 5
  failureThreshold: 24
  initialDelaySeconds: 30

readinessProbe:
  httpGet:
    port: http
    path: /healthz
  periodSeconds: 5
  failureThreshold: 3

livenessProbe:
  httpGet:
    port: http
    path: /healthz
  periodSeconds: 10
  failureThreshold: 3
 
resources:
  requests: {cpu: 250m, memory: 1000Mi}
  limits: {cpu: 250m, memory: 1000Mi}

constantsIni: |
  DOMAIN=example.invalid