schedule: "*/30 * * * *"   # iga 30 minuti järel
image:
  repository: alpine
  tag: "3.20"
  pullPolicy: IfNotPresent

command: ["/bin/sh", "-c"]
args:
  - |
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] CronJob töötas!"
    # Siia pane tegelik bash skript või käsklus

restartPolicy: OnFailure

resources: {}
