schedule: "*/30 * * * *"

image:
  repository: alpine
  tag: "3.20"
  pullPolicy: IfNotPresent
  
script:
  name: replace.sh
  content: |
    #!/bin/sh
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Asenda see asi skriptiga"

restartPolicy: OnFailure

resources: {}
