release_name: "component-byk-gui"

image:
  registry: ""
  repository: ""
  tag: ""

replicas: 1

resources:
  requests:
    memory: "500Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

env:
  NODE_ENV: "local"
  REACT_APP_RUUTER_API_URL: "http://localhost:8086"
  REACT_APP_RUUTER_PRIVATE_API_URL: "http://localhost:8088"
  REACT_APP_EXTERNAL_API_URL: "http://localhost:8000"
  REACT_APP_CUSTOMER_SERVICE_LOGIN: "http://localhost:3004/et/dev-auth"
  REACT_APP_NOTIFICATION_NODE_URL: "http://localhost:4040"
  REACT_APP_CSP: "upgrade-insecure-requests; default-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; object-src 'none'; connect-src 'self' http://localhost:8086 http://localhost:8088 http://localhost:8085 http://localhost:4040 http://localhost:3001 http://localhost:8000;"
  DEBUG_ENABLED: "true"
  CHOKIDAR_USEPOLLING: "true"
  PORT: "3001"
  REACT_APP_SERVICE_ID: "conversations,settings,monitoring"
  REACT_APP_ENABLE_HIDDEN_FEATURES: "TRUE"

volumes:
  app_node_modules:
    type: emptyDir
  gui_app:
    type: emptyDir

ingress:
  enabled: true
  host: "gui.example.com"
  path: "/"
  tls:
    enabled: true
    secretName: "gui-tls-secret"