apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: init-copy-files
          image: "{{ .Values.images.dsl.registry }}/{{ .Values.images.dsl.repository }}:{{ .Values.images.dsl.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              pwd
              cp -r ../Ruuter/ /app/DSL
              cp -r ../Resql/ /app/DSL
              cp -r ../DataMapper/ /app/DSL
              cp -r ../Liquibase/ /app/DSL
              ls -la
          volumeMounts:
            - name: analytics-dsl
              mountPath: /app/DSL
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.gui.registry }}/{{ .Values.images.gui.repository }}:{{ .Values.images.gui.tag }}"
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: REACT_APP_RUUTER_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_API_URL }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
            - name: CHOKIDAR_USEPOLLING
              value: "{{ .Values.env.CHOKIDAR_USEPOLLING }}"
            - name: REACT_APP_API_URL
              value: "{{ .Values.env.REACT_APP_API_URL }}"
            - name: REACT_APP_BUEROKRATT_CHATBOT_URL
              value: "{{ .Values.env.REACT_APP_BUEROKRATT_CHATBOT_URL }}"
            - name: REACT_APP_OPENSEARCH_DASHBOARD_URL
              value: "{{ .Values.env.REACT_APP_OPENSEARCH_DASHBOARD_URL }}" # TODO: replace
            - name: REACT_APP_OPENDATAPORT_URL
              value: "{{ .Values.env.REACT_APP_OPENDATAPORT_URL }}" # TODO: replace
            - name: REACT_APP_RUUTER_V2_PRIVATE_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_V2_PRIVATE_API_URL }}"
            - name: REACT_APP_RUUTER_V2_ANALYTICS_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_V2_ANALYTICS_API_URL }}"
            - name: REACT_APP_MENU_URL
              value: "{{ .Values.env.REACT_APP_MENU_URL }}"
            - name: REACT_APP_MENU_PATH
              value: "{{ .Values.env.REACT_APP_MENU_PATH }}"
            - name: REACT_APP_AUTH_BASE_URL
              value: "{{ .Values.env.REACT_APP_AUTH_BASE_URL }}"
            - name: REACT_APP_APP_PORT
              value: "{{ .Values.env.REACT_APP_APP_PORT }}"
            - name: REACT_APP_LOCAL
              value: "{{ .Values.env.REACT_APP_LOCAL }}"
            - name: REACT_APP_AUTH_PATH
              value: "{{ .Values.env.REACT_APP_AUTH_PATH }}"
            - name: REACT_APP_DOCKER_RUUTER
              value: "{{ .Values.env.REACT_APP_DOCKER_RUUTER }}"
            - name: REACT_APP_CUSTOMER_SERVICE_LOGIN
              value: "{{ .Values.env.REACT_APP_CUSTOMER_SERVICE_LOGIN }}"
            - name: REACT_APP_CONVERSATIONS_BASE_URL
              value: "{{ .Values.env.REACT_APP_CONVERSATIONS_BASE_URL }}"
            - name: REACT_APP_TRAINING_BASE_URL
              value: "{{ .Values.env.REACT_APP_TRAINING_BASE_URL }}"
            - name: REACT_APP_ANALYTICS_BASE_URL
              value: "{{ .Values.env.REACT_APP_ANALYTICS_BASE_URL }}"
            - name: REACT_APP_SERVICES_BASE_URL
              value: "{{ .Values.env.REACT_APP_SERVICES_BASE_URL }}"
            - name: REACT_APP_SETTINGS_BASE_URL
              value: "{{ .Values.env.REACT_APP_SETTINGS_BASE_URL }}"
            - name: REACT_APP_MONITORING_BASE_URL
              value: "{{ .Values.env.REACT_APP_MONITORING_BASE_URL }}"
            - name: REACT_APP_SERVICE_ID
              value: "{{ .Values.env.REACT_APP_SERVICE_ID }}"
            - name: REACT_APP_RUUTER_PRIVATE_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_PRIVATE_API_URL }}"
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - name: run
              mountPath: /var/run
            - name: log
              mountPath: /var/log/nginx
            - name: cache
              mountPath: /var/cache/nginx
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 7
            periodSeconds: 11
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 11
      volumes:
        - name: analytics-dsl
          persistentVolumeClaim:
            claimName: pvc-analytics-dsl
        - emptyDir: {}
          name: tmp
        - name: run
          emptyDir:
            medium: ""
        - name: log
          emptyDir:
            medium: ""
        - name: cache
          emptyDir:
            medium: ""
