apiVersion: v1
kind: PersistentVolume
metadata:
  name: analytics-{{ namespace }}-dsl-pv
spec:
  storageClassName: dsl
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
