apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ namespace }}-analytics-dsl
spec:
  storageClassName: dsl
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
