image:
  repository: registry.gitlab.ria.ee/byk/presidio-anonymizer
  # tag: dev-1.1.2
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8089
  type: ClusterIP

env:
  FLASK_ENV: production
  LOG_LEVEL: info
  HOST: "0.0.0.0"
  PORT: "8089"
  PYTHONUNBUFFERED: "1"


