apiVersion: v2
name: Buerokratt
description: Umbrella chart for Buerokratt
version: 0.1.0
type: application

dependencies:
  - name: Ruuter
    version: 0.1.0
    repository: "file://./charts/Ruuter"
  - name: Resql
    version: 0.1.0
    repository: "file://./charts/Resql"
  - name: Databases
    version: 0.1.20
    repository: "file://./charts/Databases"
  - name: Buerokratt-Chatbot
    version: 0.1.0
    repository: "file://./charts/Buerokratt-Chatbot"