apiVersion: v2
name: Buerokratt
description: Umbrella chart for Buerokratt
version: 0.1.0
type: application

dependencies:
  - name: Ruuter
    version: 0.1.0
    repository: "file://./charts/Ruuter"
  - name: Resql
    version: 0.1.0
    repository: "file://./charts/Resql"
  - name: Databases
    version: 0.1.20
    repository: "file://./charts/Databases"
  - name: Buerokratt-Chatbot
    version: 0.1.0
    repository: "file://./charts/Buerokratt-Chatbot"
  - name: TIM
    version: 0.1.0
    repository: "file://./charts/TIM"
  - name: Widget
    version: 0.1.0
    repository: "file://./charts/Widget"
  - name: Analytics-Module
    version: 0.1.0
    repository: "file://./charts/Analytics-Module"
  - name: Authentication-Layer
    version: 0.1.0
    repository: "file://./charts/Authentication-Layer"
  - name: Service-Module
    version: 0.1.0
    repository: "file://./charts/Service-Module"
  - name: Training-Module
    version: 0.1.0
    repository: "file://./charts/Training-Module"