Ruuter:
  release_name: "ruuteritest"
  domain: "eexample.com"
  images:
    scope:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/ruuter"
      # tag: "v2.2.2"
      tag: "latest"
  secretname: "ruuter.stage.buerokratt.ee0001"
  env:
    cors: "https://xample.com"
    sizelimit: "3000"
Resql:
  istio:
    enabled: false
  domain: "eexample.com"

  release_name: "component-byk-resql"
  release_db: "component-databases" 

  images:
    scope:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/resql"
      # tag: "v1.3.4"
      tag: "latest"
    backoffice:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "backoffice-module-test-1.5.19"
      tag: "latest"
    analytics:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "analytics-module-test-1.5.11"
      tag: "latest"
    services:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "service-module-test-1.5.20"
      tag: "latest"
    training:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "training-module-test-1.5.18"
      tag: "latest"
      
  env:
    LOGGING_LEVEL_ROOT: "INFO"
    SQLMS_DATASOURCES_0_NAME: "byk"
    SQLMS_DATASOURCES_0_JDBCURL: "jdbc:postgresql://component-databases-users-db:5432/byk"
    SQLMS_DATASOURCES_0_USERNAME: "byk"
    SQLMS_DATASOURCES_0_PASSWORD: ""
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT: "DEBUG"

  resources:
    requests:
      memory: "1000Mi"
      cpu: "50m"
    limits:
      memory: "2000Mi"
      cpu: "50m"

Databases:
  domain: "eexample.com"
  releaseName: "component-databases"
  tim-postgresql:
    image:
      tag: 14.1.0
    auth:
      postgresPassword: postgres
      username: tim
      password: "{{ TIMDB.password }}"
      database: tim
    statefulset:
      enabled: true
      replicaCount: 1
      persistence:
        storageClass: longhorn
        enabled: true
        size: 1Gi
  users-db:
    image:
      tag: 14.1.0
    auth:
      postgresPassword: postgres
      username: byk
      password: "{{ usersDB.password }}"
      database: byk
    statefulset:
      enabled: true
      replicaCount: 1
      persistence:
        storageClass: longhorn
        enabled: true
        size: 1Gi

Buerokratt-Chatbot:
  domain: "example.com"
  secretname: "certname"

  ingress:
    whitelistSourceRange: ""
    urlnameruuter: "https://ruuter.test.example.ee"
    urlnametim: "https://tim.test.example.ee"
    urlnameadmin: "https://admin.test.example.ee"
    
  release_name: "module-byk-backoffice-gui"

  images:
    gui:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-chatbot"
      # tag: "v1.1.1"
      tag: "latest"
    dsl:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "v1.1.1"
      tag: "latest"
    liquibase:
      dsl:
        repo: https://gitlab.ria.ee/BYK/Buerokratt-Chatbot.git
        path: DSL/Liquibase

  env:
    REACT_APP_RUUTER_API_URL: "https://ruuter.test.example.ee/v2/public/backoffice"
    REACT_APP_RUUTER_PRIVATE_API_URL: "https://ruuter.test.example.ee/v2/private/backoffice"
    REACT_APP_BUEROKRATT_CHATBOT_URL: "https://admin.test.example.ee/chat"
    REACT_APP_MENU_URL: "https://admin.test.example.ee"
    REACT_APP_MENU_PATH: "/chat/menu.json"
    REACT_APP_CUSTOMER_SERVICE_LOGIN: "https://admin.test.example.ee/et/log-in"
    DOMAIN: "test.example.ee"
    REACT_APP_CONVERSATIONS_BASE_URL: "https://admin.test.example.ee/chat"
    REACT_APP_TRAINING_BASE_URL: "https://admin.test.example.ee/training"
    REACT_APP_ANALYTICS_BASE_URL: "https://admin.test.example.ee/analytics"
    REACT_APP_SERVICES_BASE_URL: "https://admin.test.example.ee/services"
    REACT_APP_SETTINGS_BASE_URL: "https://admin.test.example.ee/settings"
    REACT_APP_MONITORING_BASE_URL: "https://admin.test.example.ee/monitoring"
    REACT_APP_SERVICE_ID: "conversations,settings,monitoring"
    REACT_APP_NOTIFICATION_NODE_URL: "https://ruuter.test.example.ee"


  liquibase:
    jdbcUrl: "jdbc:postgresql://test-buerokratt-users-db.test2.svc.cluster.local:5432/byk?user=byk"    
    dbPassword: ""

  resources:
    requests:
      memory: "10Mi"
      cpu: "1m"
    limits:
      memory: "50Mi"
      cpu: "5m"
TIM:
  domain: "eexample.com"
  secretname: "tim.centops.example.ee0001"

  release_name: "component-byk-tim"
  release_db: "component-databases"

  byk:
    tim:
      env:
        security:
          allowlist:
            jwt: component-byk-ruuter,component-byk-ruuter-private,module-byk-widget,module-byk-authentication-layer,component-byk-tim,10.0.0.0/8,192.168.0.0/16
          oauth2:
            client:
              clientId: "example" 
              clientSecret: "example"
              scope: openid
              userAuthorizationUri: "https://tim.centops.example.com/oidc/authorize"
              accessTokenUri: "https://tim.centops.example.com/oidc/token"
            resource:
              jwk:
                keySetUri: "https://tim.centops.example.com/oidc/jwks"
        legacyPortalIntegration:
          legacyUrl: NA
          legacyPortalRefererMarker: NA
          sessionCookieDomain: "eexample.com"
        jwtIntegration:
          signature:
            issuer: "eexample.com"
            keyStorePassword: "password"
            keyStore: classpath:jwtkeystore.jks
        spring:
          profiles:
            active: dev
        logging:
          level:
            root: INFO
    key_pass: "keystorepassword"
  keystore: "keystorepassword"
        
  tim-postgresql:
    image:
      tag: 14.1.0
    auth:
      postgresPassword: postgres
      username: tim
      password: "timdbpassword"
      database: "tim"

  tim_postgresql: "timdbpassword"

  images:
    scope:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/tim"
      # tag: "v1.1.1"
      tag: "latest"

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "200m"

Widget:
  domain: "test.buerokratt.ee"
  secretname: "secretnamevaartus"
  release_name: "module-byk-widget"

  images:
    gui:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/chat-widget"
      # tag: "v1.1.1"
      tag: "latest"
    dsl:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "v1.1.1"
      tag: "latest"

  config: 
    header_origin: "https://test.buerokratt.ee"

  resources:
    requests:
      memory: "10Mi"
      cpu: "1m"
    limits:
      memory: "50Mi"
      cpu: "5m"

Analytics-Module:
  domain: "test.buerokratt.ee"
  secretname: "vaartus"

  ingress:
    whitelistSourceRange: ""

  release_name: "module-byk-analytics-gui"

  images:
    gui:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/analytics-module"
      # tag: "v1.1.1"
      tag: "latest"
    dsl:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "v1.1.1"
      tag: "latest"
  env:
    REACT_APP_RUUTER_API_URL: "https://ruuter.{{ .Values.domain }}/v2/public/backoffice"
    NODE_ENV: "development"
    CHOKIDAR_USEPOLLING: "true"
    REACT_APP_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/analytics"
    REACT_APP_BUEROKRATT_CHATBOT_URL: "http://byk-bot:5005"
    REACT_APP_OPENSEARCH_DASHBOARD_URL: "https://opensearch.org/"
    REACT_APP_OPENDATAPORT_URL: "http://avaandmedtest.eesti.ee"
    REACT_APP_RUUTER_V2_PRIVATE_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice"
    REACT_APP_RUUTER_V2_ANALYTICS_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/analytics" 
    REACT_APP_MENU_URL: "https://admin.{{ .Values.domain }}"
    REACT_APP_MENU_PATH: "/chat/menu.json"
    REACT_APP_AUTH_BASE_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice"
    REACT_APP_APP_PORT: "3001"
    REACT_APP_LOCAL: "false"
    REACT_APP_DOCKER_RUUTER: "http://byk-ruuter-private:8080"
    REACT_APP_CUSTOMER_SERVICE_LOGIN: "https://admin.{{ .Values.domain }}/et/dev-auth"
    REACT_APP_CONVERSATIONS_BASE_URL: "https://admin.{{ .Values.domain }}/chat"
    REACT_APP_TRAINING_BASE_URL: "https://admin.{{ .Values.domain }}/training"
    REACT_APP_ANALYTICS_BASE_URL: "https://admin.{{ .Values.domain }}/analytics"
    REACT_APP_SERVICES_BASE_URL: "https://admin.{{ .Values.domain }}/services"
    REACT_APP_SETTINGS_BASE_URL: "https://admin.{{ .Values.domain }}/chat"
    REACT_APP_MONITORING_BASE_URL: "https://admin.{{ .Values.domain }}/monitoring"
    REACT_APP_SERVICE_ID: "analytics"
    REACT_APP_RUUTER_PRIVATE_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice"
    REACT_APP_BASE_API_PATH: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice" 
    REACT_APP_NOTIFICATION_NODE_URL: "https://ruuter.{{ .Values.domain }}"


  liquibase:
    jdbcUrl: "jdbc:postgresql://component-databases-users-db:5432/byk?user=byk"    
    dbPassword: "{{ usersDB.password }}"   # Change password accordingly

  resources:
    requests:
      memory: "10Mi"
      cpu: "1m"
    limits:
      memory: "50Mi"
      cpu: "10m"

Authentication-Layer:
  domain: "test.buerokratt.ee"
  secretname: "vaartus"

  ingress:
    whitelistSourceRange: ""

  release_name: "module-byk-authentication-layer"

  images:
    gui:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/authentication-layer"
      # tag: "v1.1.1"
      tag: "latest"
  resources:
    requests:
      memory: "10Mi"
      cpu: "1m"
    limits:
      memory: "50Mi"
      cpu: "5m"

Service-Module:
  domain: "test.buerokratt.ee"
  secretname: "vaartus"
  ingress:
    whitelistSourceRange: ""

  release_name: "module-byk-services-gui"

  images:
    gui:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/service-module"
      # tag: "v1.1.1"
      tag: "latest"
    dsl:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "v1.1.1"
      tag: "latest"

  env:
    REACT_APP_RUUTER_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice" 
    NODE_ENV: "development"
    CHOKIDAR_USEPOLLING: "true"
    REACT_APP_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/services" 
    REACT_APP_BUEROKRATT_CHATBOT_URL: "http://byk-bot:5005"
    REACT_APP_OPENSEARCH_DASHBOARD_URL: "https://opensearch.org/"
    REACT_APP_OPENDATAPORT_URL: "https://avaandmed.eesti.ee"
    REACT_APP_RUUTER_V2_PRIVATE_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice" 
    REACT_APP_RUUTER_V2_ANALYTICS_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/analytics" 
    REACT_APP_MENU_URL: "https://admin.{{ .Values.domain }}" 
    REACT_APP_MENU_PATH: "/chat/menu.json"
    REACT_APP_AUTH_BASE_URL: "https://ruuter.{{ .Values.domain }}" 
    REACT_APP_APP_PORT: "3001"
    REACT_APP_LOCAL: "false"
    REACT_APP_AUTH_PATH: "/v2/private/backoffice/custom-jwt/userinfo"
    REACT_APP_DOCKER_RUUTER: "http://byk-ruuter-private:8080"
    REACT_APP_CUSTOMER_SERVICE_LOGIN: "{https://admin.{{ .Values.domain }}/et/dev-auth" 
    REACT_APP_CONVERSATIONS_BASE_URL: "https://admin.{{ .Values.domain }}/chat" 
    REACT_APP_TRAINING_BASE_URL: "https://admin.{{ .Values.domain }}/training" 
    REACT_APP_ANALYTICS_BASE_URL: "https://admin.{{ .Values.domain }}/analytics" 
    REACT_APP_SERVICES_BASE_URL: "https://admin.{{ .Values.domain }}/services" 
    REACT_APP_SETTINGS_BASE_URL: "https://admin.{{ .Values.domain }}/chat" 
    REACT_APP_MONITORING_BASE_URL: "https://admin.{{ .Values.domain }}/monitoring" 
    REACT_APP_SERVICE_ID: "services"
    REACT_APP_RUUTER_PRIVATE_API_URL: "{{ url.name.ruuter }}/v2/private/backoffice" 
    REACT_APP_MENU_JSON: "[{\"id\":\"conversations\",\"label\":{\"et\":\"Vestlused\",\"en\":\"Conversations\"},\"path\":\"/chat\",\"children\":[{\"label\":{\"et\":\"Vastamata\",\"en\":\"Unanswered\"},\"path\":\"/unanswered\"},{\"label\":{\"et\":\"Aktiivsed\",\"en\":\"Active\"},\"path\":\"/active\"},{\"label\":{\"et\":\"Ajalugu\",\"en\":\"History\"},\"path\":\"/history\"},{\"label\":{\"et\":\"Ootel\",\"en\":\"Pending\"},\"path\":\"/pending\"}]},{\"id\":\"training\",\"label\":{\"et\":\"Treening\",\"en\":\"Training\"},\"path\":\"/training\",\"children\":[{\"label\":{\"et\":\"Treening\",\"en\":\"Training\"},\"path\":\"/training\",\"children\":[{\"label\":{\"et\":\"Teemad\",\"en\":\"Themes\"},\"path\":\"/training/intents\"},{\"label\":{\"et\":\"Avalikud teemad\",\"en\":\"Public themes\"},\"path\":\"/training/common-intents\"},{\"label\":{\"et\":\"Teemade järeltreenimine\",\"en\":\"Post training themes\"},\"path\":\"/training/intents-followup-training\"},{\"label\":{\"et\":\"Vastused\",\"en\":\"Answers\"},\"path\":\"/training/responses\"},{\"label\":{\"et\":\"Kasutuslood\",\"en\":\"User Stories\"},\"path\":\"/training/stories\"},{\"label\":{\"et\":\"Konfiguratsioon\",\"en\":\"Configuration\"},\"path\":\"/training/configuration\"},{\"label\":{\"et\":\"Vormid\",\"en\":\"Forms\"},\"path\":\"/training/forms\"},{\"label\":{\"et\":\"Mälukohad\",\"en\":\"Slots\"},\"path\":\"/training/slots\"},{\"label\":{\"et\":\"Automatic Teenused\",\"en\":\"Automatic Services\"},\"path\":\"/auto-services\"}]},{\"label\":{\"et\":\"Ajaloolised vestlused\",\"en\":\"Historical conversations\"},\"path\":\"/history\",\"children\":[{\"label\":{\"et\":\"Ajalugu\",\"en\":\"History\"},\"path\":\"/history/history\"},{\"label\":{\"et\":\"Pöördumised\",\"en\":\"Appeals\"},\"path\":\"/history/appeal\"}]},{\"label\":{\"et\":\"Mudelipank ja analüütika\",\"en\":\"Modelbank and analytics\"},\"path\":\"/analytics\",\"children\":[{\"label\":{\"et\":\"Teemade ülevaade\",\"en\":\"Overview of topics\"},\"path\":\"/analytics/overview\"},{\"label\":{\"et\":\"Mudelite võrdlus\",\"en\":\"Comparison of models\"},\"path\":\"/analytics/models\"},{\"label\":{\"et\":\"Testlood\",\"en\":\"testTracks\"},\"path\":\"/analytics/testcases\"}]},{\"label\":{\"et\":\"Treeni uus mudel\",\"en\":\"Train new model\"},\"path\":\"/train-new-model\"}]},{\"id\":\"analytics\",\"label\":{\"et\":\"Analüütika\",\"en\":\"Analytics\"},\"path\":\"/analytics\",\"children\":[{\"label\":{\"et\":\"Ülevaade\",\"en\":\"Overview\"},\"path\":\"/overview\"},{\"label\":{\"et\":\"Vestlused\",\"en\":\"Chats\"},\"path\":\"/chats\"},{\"label\":{\"et\":\"Bürokratt\",\"en\":\"Burokratt\"},\"path\":\"/burokratt\"},{\"label\":{\"et\":\"Tagasiside\",\"en\":\"Feedback\"},\"path\":\"/feedback\"},{\"label\":{\"et\":\"Nõustajad\",\"en\":\"Advisors\"},\"path\":\"/advisors\"},{\"label\":{\"et\":\"Avaandmed\",\"en\":\"Reports\"},\"path\":\"/reports\"}]},{\"id\":\"services\",\"label\":{\"et\":\"Teenused\",\"en\":\"Services\"},\"path\":\"/services\",\"children\":[{\"label\":{\"et\":\"Ülevaade\",\"en\":\"Overview\"},\"path\":\"/overview\"},{\"label\":{\"et\":\"Uus teenus\",\"en\":\"New Service\"},\"path\":\"/newService\"},{\"label\":{\"et\":\"Automatic Teenused\",\"en\":\"Automatic Services\"},\"path\":\"/auto-services\"},{\"label\":{\"et\":\"Probleemsed teenused\",\"en\":\"Faulty Services\"},\"path\":\"/faultyServices\"}]},{\"id\":\"settings\",\"label\":{\"et\":\"Haldus\",\"en\":\"Administration\"},\"path\":\"/settings\",\"children\":[{\"label\":{\"et\":\"Kasutajad\",\"en\":\"Users\"},\"path\":\"/users\"},{\"label\":{\"et\":\"Vestlusbot\",\"en\":\"Chatbot\"},\"path\":\"/chatbot\",\"children\":[{\"label\":{\"et\":\"Seaded\",\"en\":\"Settings\"},\"path\":\"/chatbot/settings\"},{\"label\":{\"et\":\"Tervitussõnum\",\"en\":\"Welcome message\"},\"path\":\"/chatbot/welcome-message\"},{\"label\":{\"et\":\"Välimus ja käitumine\",\"en\":\"Appearance and behavior\"},\"path\":\"/chatbot/appearance\"},{\"label\":{\"et\":\"Erakorralised teated\",\"en\":\"Emergency notices\"},\"path\":\"/chatbot/emergency-notices\"}]},{\"label\":{\"et\":\"Asutuse tööaeg\",\"en\":\"Office opening hours\"},\"path\":\"/working-time\"},{\"label\":{\"et\":\"Sessiooni pikkus\",\"en\":\"Session length\"},\"path\":\"/session-length\"}]},{\"id\":\"monitoring\",\"label\":{\"et\":\"Seire\",\"en\":\"Monitoring\"},\"path\":\"/monitoring\",\"children\":[{\"label\":{\"et\":\"Aktiivaeg\",\"en\":\"Working hours\"},\"path\":\"/uptime\"}]}]"

  liquibase:
    jdbcUrl: "jdbc:postgresql://component-databases-users-db:5432/byk?user=byk"    
    dbPassword: "{{ usersDB.password }}"  # Change password accordingly

  resources:
    requests:
      memory: "10Mi"
      cpu: "1m"
    limits:
      memory: "50Mi"
      cpu: "5m"

Training-Module:
  domain: "test.buerokratt.ee"  
  secretname: "vaartus"
  ingress:
    whitelistSourceRange: ""
  release_name: "module-byk-training-gui"
  images:
    gui:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/training-module"
      # tag: "v1.1.1"
      tag: "latest"
    dsl:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/buerokratt-dsl"
      # tag: "v1.1.1"
      tag: "latest"
    pipelines:
      registry: "registry.gitlab.ria.ee"
      repository: "byk/training-module"
      # tag: "v1.1.1"
      tag: "latest"
      

  env:
    REACT_APP_RUUTER_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice" 
    NODE_ENV: "development"
    CHOKIDAR_USEPOLLING: "true"
    REACT_APP_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/training" 
    REACT_APP_BUEROKRATT_CHATBOT_URL: "http://byk-bot:5005"
    REACT_APP_OPENSEARCH_DASHBOARD_URL: "https://opensearch.org/"
    REACT_APP_OPENDATAPORT_URL: "https://avaandmed.eesti.ee"
    REACT_APP_RUUTER_V2_PRIVATE_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice" 
    REACT_APP_RUUTER_V2_ANALYTICS_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/analytics" 
    REACT_APP_MENU_URL: "https://admin.{{ .Values.domain }}" 
    REACT_APP_MENU_PATH: "/chat/menu.json"
    REACT_APP_AUTH_BASE_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice" 
    REACT_APP_APP_PORT: "3001"
    REACT_APP_LOCAL: "false"
    REACT_APP_DOCKER_RUUTER: "http://byk-ruuter-private:8080"
    REACT_APP_CUSTOMER_SERVICE_LOGIN: "https://admin.{{ .Values.domain }}/et/dev-auth" 
    REACT_APP_CONVERSATIONS_BASE_URL: "https://admin.{{ .Values.domain }}/chat" 
    REACT_APP_TRAINING_BASE_URL: "https://admin.{{ .Values.domain }}/training" 
    REACT_APP_ANALYTICS_BASE_URL: "https://admin.{{ .Values.domain }}/analytics" 
    REACT_APP_SERVICES_BASE_URL: "https://admin.{{ .Values.domain }}/services" 
    REACT_APP_SETTINGS_BASE_URL: "https://admin.{{ .Values.domain }}/chat" 
    REACT_APP_MONITORING_BASE_URL: "https://admin.{{ .Values.domain }}/monitoring" 
    REACT_APP_SERVICE_ID: "training"
    REACT_APP_RUUTER_PRIVATE_API_URL: "https://ruuter.{{ .Values.domain }}/v2/private/backoffice" 
    REACT_APP_BASE_URL: "byrokratt/"
    REACT_APP_SERVICE_MODULE_GUI_BASE_URL: "https://admin.{{ .Values.domain }}/services/" 
    REACT_APP_NODE_ENV: "development"
    REACT_APP_RUUTER_URL: "https://ruuter.{{ .Values.domain }}/v2/private/training/" 
    REACT_APP_RUUTER_URL: "https://ruuter.{{ .Values.domain }}/v2/private/training/"
    REACT_APP_SERVICE_MODULE_GUI_BASE_URL: "http://module-byk-services-gui:3006"
    REACT_APP_NOTIFICATION_NODE_URL: "https://ruuter.{{ .Values.domain }}"

  liquibase:
    jdbcUrl: "jdbc:postgresql://component-databases-users-db:5432/byk?user=byk"    
    dbPassword: "{{ usersDB.password }}"  # Change password accordingly

  resources:
    training:
      requests:
        memory: "100Mi"
        cpu: "1m"
      limits:
        memory: "125Mi"
        cpu: "5m"
    pipeline:
      requests:
        memory: "100Mi"
        cpu: "1m"
      limits:
        memory: "256Mi"
        cpu: "5m"