Ruuter:
  release_name: "ruuteritest"
  domain: "eexample.com"
  replicas: 1
  images:
    scope:
      registry: "ghcr.io"
      repository: "buerokratt/ruuter"
      tag: "v2.2.2"
  certIssuerName: "letsencrypt-prod"
  secretname: "ruuter.stage.buerokratt.ee0001"
  env:
    cors: "https://xample.com"
    sizelimit: "3000"
