global:
  istio:
    enabled: true

  domain: "example.com"

  ingress:
    certIssuerName: "letsencrypt-prod"

  images:
    scope:
      registry: "ghcr.io"
      repository: "buerokratt/resql"
      tag: "v1.0.0"
    backoffice:
      registry: "ghcr.io"
      repository: "buerokratt/buerokratt-dsl"
      tag: "v1.0.0"
    analytics:
      registry: "ghcr.io"
      repository: "buerokratt/buerokratt-dsl"
      tag: "v1.0.0"
    services:
      registry: "ghcr.io"
      repository: "buerokratt/buerokratt-dsl"
      tag: "v1.0.0"
    training:
      registry: "ghcr.io"
      repository: "buerokratt/buerokratt-dsl"
      tag: "v1.0.0"

  env:
    LOGGING_LEVEL_ROOT: "INFO"
    SQLMS_DATASOURCES_0_NAME: "byk"
    SQLMS_DATASOURCES_0_JDBCURL: "jdbc:postgresql://component-databases-users-db:5432/byk"
    SQLMS_DATASOURCES_0_USERNAME: "" # Example: <path:kv/data/apps/component-byk-resql/db-creds#SQLMS_DATASOURCES_0_USERNAME>
    SQLMS_DATASOURCES_0_PASSWORD: "" # Example: <path:kv/data/apps/component-byk-resql/db-creds#SQLMS_DATASOURCES_0_PASSWORD>
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT: "DEBUG"

  resources:
    requests:
      memory: "1000Mi"
      cpu: "50m"
    limits:
      memory: "2000Mi"
      cpu: "50m"

component-byk-resql:
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  replicas: 1
  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  release_name: "component-byk-resql"
  release_db: "component-databases"

component-databases:
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  releaseName: "component-databases"

  tim-postgresql:
    image:
      tag: "14.1.0"
    auth:
      postgresPassword: "postgres"
      username: "tim"
      password: "tim-db-password"
      database: "tim"
    statefulset:
      enabled: true
      replicaCount: 1
      persistence:
        storageClass: "longhorn"
        enabled: true
        size: "1Gi"

  users-db:
    image:
      tag: "14.1.0"
    auth:
      postgresPassword: "postgres"
      username: "byk"
      password: "users-db-password"
      database: "byk"
    statefulset:
      enabled: true
      replicaCount: 1
      persistence:
        storageClass: "longhorn"
        enabled: true
        size: "1Gi"
