apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seaweedfs.fullname" . }}-s3
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3.json: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": {{ .Values.s3.credentials.accessKey | quote }},
              "secretKey": {{ .Values.s3.credentials.secretKey | quote }}
            }
          ],
          "actions": ["Admin", "Read", "Write", "List", "Tagging"]
        }
      ]
    }
