nameOverride: module-byk-services-gui
fullnameOverride: module-byk-services-gui
replicaCount: 1
 
workload:
  kind: Deployment
  selectorLabels: {app: module-byk-services-gui}
 
image:
  repository: ghcr.io
  name: buerokratt/service-module
  tag: "v3.3.2"
  pullPolicy: IfNotPresent
 
containerPorts:
  - {name: http, containerPort: 3006}
 
env: []
 
resources:
  requests: {cpu: 1m, memory: 10Mi}
  limits: {cpu: 5m, memory: 50Mi}
 
services:
  http:
    name: module-byk-services-gui
    ports:
      http: {port: 3006, targetPort: http, protocol: TCP}
 
ingress: {enabled: false}
istio: {enabled: false}
 
constantsIni: |
  NODE_ENV=development