imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicas: 1
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: {{ domain.name }} # Domain name
secretname: {{ cert.Name.value }} # Cert name value, change this as suited to environment

ingress:
  certIssuerName: {{ cert.Issuer.Name }} # Change this if your certIssuerName has set up different

release_name: "component-notification-node"  

images:
  scope:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-chatbot"
    tag: "{{ component.notification.node.image.version }}" # Images (tags) are up to date, currently no changes needed

env:
  OPENSEARCH_PROTOCOL: "http"
  OPENSEARCH_HOST: "component-opensearch-node"
  OPENSEARCH_PORT: "9200"
  OPENSEARCH_USERNAME: "admin"
  OPENSEARCH_PASSWORD: "admin"
  PORT: "4040"
  REFRESH_INTERVAL: "1000"
  CORS_WHITELIST_ORIGINS: "http://module-byk-widget:3001,http://module-byk-backoffice-gui:3000,http://component-byk-ruuter-private:8080,http://component-byk-ruuter:8080"
  RUUTER_URL: http://component-byk-ruuter:8080
  CHAT_TERMINATION_DELAY: "5000"

resources:
  requests:
    memory: "60Mi"
    cpu: "200m"
  limits:
    memory: "256Mi"
    cpu: "200m"
