apiVersion: v2
name: ckb
description: Helm chart for the Common Knowledge Base (CKB) application.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
- byk
- ckb
- ruuter
- opensearch
- postgres
- rabbitmq